The integration of CXF into the https://quarkus.io/guides/micrometer[Quarkus Micrometer] ecosystem is implemented using
`io.quarkiverse.cxf.metrics.QuarkusCxfMetricsFeature`.
As long as your application depends on `quarkus-cxf-rt-features-metrics`,
an instance of `QuarkusCxfMetricsFeature` is created internally
and enabled by default for all clients and service endpoints created by {quarkus-cxf-project-name}.
You can disable it via `quarkus.cxf.metrics.enabled-for`, `quarkus.cxf.client."clients".metrics.enabled`
and `quarkus.cxf.endpoint."endpoints".metrics.enabled` properties documented below.

=== Runnable example

There is an https://github.com/quarkiverse/quarkus-cxf/tree/main/integration-tests/metrics[integration test]
covering Micrometer Metrics in the {quarkus-cxf-project-name} source tree.

Unsurprisingly, it depends on `quarkus-cxf-rt-features-metrics`

.pom.xml
[source,xml]
----
<dependency>
    <groupId>io.quarkiverse.cxf</groupId>
    <artifactId>quarkus-cxf-rt-features-metrics</artifactId>
</dependency>
----

It is using `quarkus-micrometer-registry-prometheus` extension to export the metrics in JSON format and for Prometheus:

.pom.xml
[source,xml]
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-micrometer-registry-prometheus</artifactId>
</dependency>
----

The following configuration is needed to be able to inspect the collected metrics over a REST endpoint:

.application.properties
[source,properties]
----
include::example$metrics/application.properties[tag=micrometer-export]
----

Having all the above in place, you can start the application in Dev mode:

[source,shell]
----
$ mvn quarkus:dev
----

Now send a request to the `HelloService`:

[source,shell]
----
$ curl \
  -d '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ns2:helloResponse xmlns:ns2="http://it.server.metrics.cxf.quarkiverse.io/"><return>Hello Joe!</return></ns2:helloResponse></soap:Body></soap:Envelope>' \
  -H 'Content-Type: text/xml' \
  -X POST \
  http://localhost:8080/metrics/client/hello
----

After that, you should see some metrics under `cxf.server.requests` in the output of the endpoint you configured above:

[source,shell]
----
$ curl http://localhost:8080/q/metrics/json
metrics: {
    ...
    "cxf.server.requests": {
        "count;exception=None;faultCode=None;method=POST;operation=hello;outcome=SUCCESS;status=200;uri=/soap/hello": 2,
        "elapsedTime;exception=None;faultCode=None;method=POST;operation=hello;outcome=SUCCESS;status=200;uri=/soap/hello": 64.0
    },
    ...
}
----
