Once the `quarkus-cxf-rt-transports-http-hc5` dependency is available in the classpath,
CXF will use `HttpAsyncClient` for asynchronous calls and will continue using `HttpURLConnection` for synchronous calls.

=== Thread pool

Asynchronous clients delivered by this extension leverage `ManagedExecutor` with a thread pool provided by Quarkus.
The thread pool can be configured using the `quarkus.thread-pool.*` family of
{link-quarkus-docs-base}/all-config#quarkus-core_quarkus-thread-pool-core-threads[options].
As a consequence of this, the executor and thread pool related attributes of `org.apache.cxf.transports.http.configuration.HTTPClientPolicy` are not honored for async clients on Quarkus.

[TIP]
====
You can see more details about the CXF asynchronous client and how to tune it further in https://cxf.apache.org/docs/asynchronous-client-http-transport.html[CXF documentation].
====

=== See also

* xref:user-guide/advanced-client-topics/asynchronous-client.adoc[Synchronous vs. Asynchronous client]
