Once the `quarkus-cxf-rt-transports-http-hc5` dependency is available in the classpath,
CXF will use `HttpAsyncClient` for asynchronous calls and will continue using `HttpURLConnection` for synchronous calls.


[[wsdl2java]]
=== Generate async methods

Asynchronous client invocations require some additional methods in the service endpoint interface.
That code is not generated by default.

To enable it, you need to create a JAX-WS binding file with `enableAsyncMapping` set to `true`:

TIP: The sample code snippets used in this section come from the
     https://github.com/quarkiverse/quarkus-cxf/tree/main/integration-tests/hc5[HC5 integration test]
     in the source tree of {quarkus-cxf-project-name}

.src/main/resources/wsdl/async-binding.xml
[source,xml]
----
include::example$hc5/async-binding.xml[]
----

This file should then be passed to xref:user-guide/generate-java-from-wsdl.adoc[wsdl2java]
through its xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus.cxf.codegen.wsdl2java.additional-params[additional-params] property:

.application.properties
[source,properties]
----
include::example$hc5/application.properties[tag=quarkus-cxf-rt-transports-http-hc5.usage.wsdl2java]
----

[[async-uni]]
=== Asynchronous Clients and Mutiny

Once the asynchronous stubs are available, it is possible to wrap a client call in `io.smallrye.mutiny.Uni` as shown below:

[source,java]
----
include::example$hc5/Hc5Resource.java[tag=quarkus-cxf-rt-transports-http-hc5.usage.mutiny]
----

=== Thread pool

Asynchronous clients delivered by this extension leverage `ManagedExecutor` with a thread pool provided by Quarkus.
The thread pool can be configured using the `quarkus.thread-pool.*` family of
https://quarkus.io/guides/all-config#quarkus-core_quarkus.thread-pool.core-threads[options].
As a consequence of this, the executor and thread pool related attributes of `org.apache.cxf.transports.http.configuration.HTTPClientPolicy` are not honored for async clients on Quarkus.

TIP: You can see more details about the CXF asynchronous client and how to tune it further in https://cxf.apache.org/docs/asynchronous-client-http-transport.html[CXF documentation].
