# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# See the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # these have the @sync annotation in pom.xml
      - dependency-name: 'com.sun.xml.messaging.saaj:*'
      - dependency-name: 'io.smallrye.certs:*'
      - dependency-name: 'jakarta.mail:*'
      - dependency-name: 'jakarta.jws:*'
      - dependency-name: 'jakarta.xml.soap:*'
      - dependency-name: 'jakarta.xml.ws:*'
      - dependency-name: 'org.codehaus.woodstox:*'
      - dependency-name: 'org.glassfish.jaxb:*'
      - dependency-name: 'org.apache.cxf.xjcplugins:*'
      - dependency-name: 'org.apache.cxf.xjc-utils:*'
      - dependency-name: 'org.apache.neethi:*'
      - dependency-name: 'org.slf4j:*'

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
