= SOAP payload logging feature

include::../includes/attributes.adoc[]

This extension helps with outputting requests and responses including HTTP headers and SOAP payloads for both CXF clients and services.

Maven users will need to add the following dependency to their `pom.xml`:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.cxf</groupId>
    <artifactId>quarkus-cxf-rt-features-logging</artifactId>
</dependency>
----

TIP: Check the xref:user-guide/create-project.adoc#dependency-management[dependency management] section.

The `quarkus-cxf-rt-features-logging` extension wraps the CXF `org.apache.cxf:cxf-rt-features-logging` artifact
which in turn provides the `org.apache.cxf.ext.logging.LoggingFeature` class.

`LoggingFeature` instances can be configured per service or client.
You can either use a `LoggingFeature` instance with default settings
or you can produce a custom `LoggingFeature` CDI bean.

== Attaching `LoggingFeature` to a client or service

You have two options to do that:

1. In `application.properties`:
+
[source,properties,subs=attributes+]
----
# For a service:
quarkus.cxf.endpoint."/hello".features=org.apache.cxf.ext.logging.LoggingFeature
# For a client:
quarkus.cxf.client."myClient".features=org.apache.cxf.ext.logging.LoggingFeature
----
+
or alternatively
+
2. Use the `@Features` annotation of CXF:
+
[source,java]
----
@org.apache.cxf.feature.Features (features = {"org.apache.cxf.ext.logging.LoggingFeature"})
@WebService(endpointInterface = "org.acme.SayHi", targetNamespace = "uri:org.acme")
public class SayHiImplementation implements SayHi {
   public long sayHi(long arg) {
       return arg;
   }
   //...
}
----

== Custom `LoggingFeature`

`LoggingFeature` offers some attributes that may be worth customizing in some situations.

E.g. if your payloads are complex, you may want to set `prettyLogging` to `true` to render them with an indentation.
Or if your messages are big and you need to see them complete in the log, you may want to increase the `limit`.

TIP: Check the CXF https://cxf.apache.org/docs/message-logging.html[message logging] page for all possible `LoggingFeature` attributes.

To achieve this, you can produce a custom `LoggingFeature` bean that is then picked by Quarkus CXF
for clients and services where you specified `*.features = org.apache.cxf.ext.logging.LoggingFeature`:

[source,java]
----
import org.apache.cxf.ext.logging.LoggingFeature;

import io.quarkus.arc.Unremovable;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.inject.Produces;

class Producers {

    @Produces
    @ApplicationScoped
    LoggingFeature loggingFeature() {
        LoggingFeature loggingFeature = new LoggingFeature();
        loggingFeature.setPrettyLogging(true);
        loggingFeature.setLimit(Integer.MAX_VALUE);
        return loggingFeature;
    }
}
----

=== Multiple custom `LoggingFeature`s

In case you'd like to configure the `LoggingFeature`s for your individual services or clients differently,
you can so that by defining multiple `@Named` `LoggingFeature` beans:

[source,java]
----
import org.apache.cxf.ext.logging.LoggingFeature;

import io.quarkus.arc.Unremovable;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.inject.Produces;

class Producers {

    @Produces
    @ApplicationScoped
    @Named("limitedLoggingFeature") // "limitedLoggingFeature" is redundant if the name of the method is the same
    LoggingFeature limitedLoggingFeature() {
        LoggingFeature loggingFeature = new LoggingFeature();
        loggingFeature.setLimit(Integer.MAX_VALUE);
        return loggingFeature;
    }

    @Produces
    @ApplicationScoped
    @Named("prettyLoggingFeature")
    LoggingFeature prettyLoggingFeature() {
        LoggingFeature loggingFeature = new LoggingFeature();
        loggingFeature.setPrettyLogging(true);
        return loggingFeature;
    }
}
----

and then refer to them by their names prefixed with `#` in `application.properties`:

[source,properties,subs=attributes+]
----
# For a service:
quarkus.cxf.endpoint."/hello".features = #limitedLoggingFeature
# For a client:
quarkus.cxf.client."myClient".features = #prettyLoggingFeature
----


== See also

* xref:reference/configuration-properties.adoc[Configuration properties] reference
* An example in xref:user-guide/first-soap-web-service.adoc#logging-feature[Your first SOAP Web service] chapter of the User guide.
