package io.quarkiverse.cxf.it.redirect.retransmitcache;

import java.net.URL;

import javax.xml.namespace.QName;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-11-21T16:40:52.628+01:00
 * Generated source version: 4.0.5
 *
 */
@WebServiceClient(name = "RetransmitCacheService", wsdlLocation = "file:/home/ppalaga/orgs/cxf/qcxf/integration-tests/client-server/src/main/resources/wsdl/RetransmitCache.wsdl", targetNamespace = "https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/test")
public class RetransmitCacheService_Service extends Service {

    public static final QName SERVICE = new QName("https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/test",
            "RetransmitCacheService");
    public static final QName RetransmitCacheServiceImplPort = new QName(
            "https://quarkiverse.github.io/quarkiverse-docs/quarkus-cxf/test", "RetransmitCacheServiceImplPort");

    public RetransmitCacheService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RetransmitCacheService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *         returns RetransmitCacheService
     */
    @WebEndpoint(name = "RetransmitCacheServiceImplPort")
    public RetransmitCacheService getRetransmitCacheServiceImplPort() {
        return super.getPort(RetransmitCacheServiceImplPort, RetransmitCacheService.class);
    }

    /**
     *
     * @param features
     *        A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the
     *        <code>features</code> parameter will have their default values.
     * @return
     *         returns RetransmitCacheService
     */
    @WebEndpoint(name = "RetransmitCacheServiceImplPort")
    public RetransmitCacheService getRetransmitCacheServiceImplPort(WebServiceFeature... features) {
        return super.getPort(RetransmitCacheServiceImplPort, RetransmitCacheService.class, features);
    }

}
