[[cxf-extension-for-quarkus]]
= {quarkus-cxf-project-name}

This project aims at porting http://cxf.apache.org/[Apache CXF] to https://quarkus.io/[Quarkus] runtime
including full support for producing https://quarkus.io/container-first/[GraalVM native images].

http://cxf.apache.org/[Apache CXF] is a framework for developing Web services.
It implements a number of standards and specifications.
{quarkus-cxf-project-name} is currently focusing only on supporting the ones related to
Simple Object Access Protocol (https://en.wikipedia.org/wiki/SOAP[SOAP])
and Java API for XML Web Services (https://en.wikipedia.org/wiki/JAX-WS[JAX-WS]).

The documentation is divided in two major parts:

* xref:user-guide/index.adoc[User guide] - explains the typical usage of {quarkus-cxf-project-name}
* xref:reference/index.adoc[Reference] - the full list of supported specifications and configuration options

[[issues-and-support]]
== Issues and Support

Please feel free to https://github.com/quarkiverse/quarkus-cxf/discussions[start a  discussion]
or https://github.com/quarkiverse/quarkus-cxf/issues/new[open an issue] in the GitHub repository in case you need support.
The following general guidelines can be used to determine whether to start a discussion or open an issue.

=== https://github.com/quarkiverse/quarkus-cxf/issues[GitHub Issues]

- Bug reports
- Feature requests

=== https://github.com/quarkiverse/quarkus-cxf/discussions[GitHub Discussions]

- Q&A and general communication
- RFCs for new features

Contributions and pull requests from the community are welcome!
