[[quarkus-cxf-index]]
= {quarkus-cxf-project-name}

This project aims at porting http://cxf.apache.org/[Apache CXF] to https://quarkus.io/[Quarkus] runtime
including full support for producing https://quarkus.io/container-first/[GraalVM native images].

[IMPORTANT]
====
While http://cxf.apache.org/[Apache CXF] implements wide range of standards and specifications,
{quarkus-cxf-project-name} is currently focusing *only* on supporting the ones related to
*Simple Object Access Protocol* (https://en.wikipedia.org/wiki/SOAP[SOAP])
and *Java API for XML Web Services* (https://en.wikipedia.org/wiki/JAX-WS[JAX-WS]).
Refer to xref:reference/index.adoc#reference-index[Reference] to learn which parts of CXF are supported.
====

The documentation is divided into the following main parts:

* xref:user-guide/index.adoc#user-guide-index[User guide] - explains the typical usage of {quarkus-cxf-project-name}
* xref:security-guide/index.adoc#security-guide-index[Security guide] - documents various security related aspects of {quarkus-cxf-project-name}, such as SSL/TLS, Authentication and Authorization
* xref:release-notes/index.adoc#release-notes-index[Release notes] - Release notes documents for the past releases
* xref:release-planning.adoc#release-planning[Release planning] - when new releases of {quarkus-cxf-project-name} are to be expected
* xref:reference/index.adoc#reference-index[Reference] - the full list of supported specifications, use cases and configuration options

[[issues-and-support]]
== Issues and Support

Feel free to https://github.com/quarkiverse/quarkus-cxf/discussions[start a  discussion]
or https://github.com/quarkiverse/quarkus-cxf/issues/new[open an issue] in the GitHub repository in case you need support.
The following general guidelines can be used to determine whether to start a discussion or open an issue.

=== https://github.com/quarkiverse/quarkus-cxf/issues[GitHub Issues]

- Bug reports
- Feature requests

=== https://github.com/quarkiverse/quarkus-cxf/discussions[GitHub Discussions]

- Q&A and general communication
- RFCs for new features

Contributions and pull requests from the community are welcome!
