[[properties_reference]]
= Properties Reference

[.configuration-reference.searchable, cols="50,.^20,.^30"]
|===

h|Configuration property
h|Type
h|Notes

a| [[quarkus.cxf.path]]`link:#quarkus.cxf.path[quarkus.cxf.path]`

[.description]
--
Root context for CXF web services
--|String
|If REST API is used, split REST and SOAP with different paths to make wsdl url working.

a| [[quarkus.cxf.wsdl-path]]`link:#quarkus.cxf.path[quarkus.cxf.wsdl-path]`

[.description]
--
The paths of wsdl include in resource
--|String
|The comma-separated list of wsdl resource path used by cxf.(for native support)

a| [[quarkus.cxf.endpoint.key.features]]`link:#quarkus.cxf.endpoint.key.features[quarkus.cxf.endpoint.key.features]`

[.description]
--
The comma-separated list of Feature classes
--|List of Strings
|

a| [[quarkus.cxf.endpoint.key.implementor]]`link:#quarkus.cxf.endpoint.key.implementor[quarkus.cxf.endpoint.key.implementor]`

[.description]
--
The server class implementor
--|String
|

a| [[quarkus.cxf.endpoint.key.in-fault-interceptors]]`link:#quarkus.cxf.endpoint.key.in-fault-interceptors[quarkus.cxf.endpoint.key.in-fault-interceptors]`

[.description]
--
The comma-separated list of InFaultInterceptor classes
--|List of Strings
|

a| [[quarkus.cxf.endpoint.key.in-interceptors]]`link:#quarkus.cxf.endpoint.key.in-interceptors[quarkus.cxf.endpoint.key.in-interceptors]`

[.description]
--
The comma-separated list of InInterceptor classes
--|List of Strings
|

a| [[quarkus.cxf.endpoint.key.out-fault-interceptors]]`link:#quarkus.cxf.endpoint.key.out-fault-interceptors[quarkus.cxf.endpoint.key.out-fault-interceptors]`

[.description]
--
The comma-separated list of OutFaultInterceptor classes
--|List of Strings
|

a| [[quarkus.cxf.endpoint.key.out-interceptors]]`link:#quarkus.cxf.endpoint.key.out-interceptors[quarkus.cxf.endpoint.key.out-interceptors]`

[.description]
--
The comma-separated list of OutInterceptor classes
--|List of Strings
|

a| [[quarkus.cxf.endpoint.key.published-endpoint-url]]`link:#quarkus.cxf.endpoint.key.published-endpoint-url[quarkus.cxf.endpoint.key.published-endpoint-url]`

[.description]
--
The server endpoint URL
--|String
|

a| [[quarkus.cxf.endpoint.key.wsdl]]`link:#quarkus.cxf.endpoint.key.wsdl[quarkus.cxf.endpoint.key.wsdl]`

[.description]
--
WSDL resource path used by CXF
--|String
|


a| [[quarkus.cxf.endpoint.key.soap-binding]]`link:#quarkus.cxf.endpoint.key.soap-binding[quarkus.cxf.endpoint.key.soap-binding]`

[.description]
--
SOAP version (1.1 by default)
--|String
|
* SOAP 1.1 : http://schemas.xmlsoap.org/wsdl/soap/http +
* SOAP 1.2 : http://www.w3.org/2003/05/soap/bindings/HTTP/ +
* SOAP 1.1 with MTOM : http://schemas.xmlsoap.org/wsdl/soap/http?mtom=true +
* SOAP 1.2 with MTOM : http://www.w3.org/2003/05/soap/bindings/HTTP/?mtom=true
|===