[[authentication-authorization]]
= Authentication and authorization

[NOTE]
====
The sample code snippets shown in this section come from the
https://github.com/quarkiverse/quarkus-cxf/tree/main/integration-tests/client-server[Client and server integration test]
in the source tree of {quarkus-cxf-project-name}. You may want to use it as a runnable example.
====

[[client-http-basic-authentication]]
== Client HTTP basic authentication

Use the following client configuration options provided by
`xref:reference/extensions/quarkus-cxf.adoc[quarkus-cxf]` extension
to pass the username and password for HTTP basic authentication:

* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-username[quarkus.cxf.client."client-name".username]`
* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-password[quarkus.cxf.client."client-name".password]`

Here is an example:

.application.properties
[source,properties]
----
include::example$client-server/application.properties[tag=client-basic-auth]
----

=== Accessing WSDL protected by basic authentication

By default, the clients created by {quarkus-cxf-project-name} do not send the `Authorization` header,
unless you set the `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-secure-wsdl-access[quarkus.cxf.client."client-name".secure-wsdl-access]` to `true`:

.application.properties
[source,properties]
----
include::example$client-server/application.properties[tag=client-basic-auth-wsdl]
----

== Mutual TLS (mTLS) authentication

See the xref:user-guide/ssl-tls-https.adoc#mtls[Mutual TLS (mTLS) authentication] section in SSL, TLS and HTTPS guide.

[[securing-service-endpoints]]
== Securing service endpoints

The server-side authentication and authorization is driven by {link-quarkus-docs-base}/security-overview[Quarkus Security],
especially when it comes to

* {link-quarkus-docs-base}/security-authentication-mechanisms[Authentication mechanisms]
* {link-quarkus-docs-base}/security-identity-providers[Identity providers]
* {link-quarkus-docs-base}/security-authorize-web-endpoints-reference[Role-based access control (RBAC)]

There is a basic example in our https://github.com/quarkiverse/quarkus-cxf/tree/main/integration-tests/client-server[Client and server integration test].
Its key parts are:

* `io.quarkus:quarkus-elytron-security-properties-file` dependency as an Identity provider
* Basic authentication enabled and users with their roles configured in `application.properties`:
+
.application.properties
[source,properties]
----
include::example$client-server/application.properties[tag=users-and-roles]
----
+
* Role-based access control enfoced via `@RolesAllowed` annotation:

.BasicAuthHelloServiceImpl.java
[source,properties]
----
include::example$client-server/BasicAuthHelloServiceImpl.java[]
----
