= Authentication and authorization

[NOTE]
====
The sample code snippets shown in this section come from the
https://github.com/quarkiverse/quarkus-cxf/tree/main/integration-tests/client-server[Client and server integration test]
in the source tree of {quarkus-cxf-project-name}. You may want to use it as a runnable example.
====

[id="client_http_basic_authentication"]
== Client HTTP basic authentication

Use the following client configuration options provided by
`xref:reference/extensions/quarkus-cxf.adoc[quarkus-cxf]` extension
to pass the username and password for HTTP basic authentication:

* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-clients-username[quarkus.cxf.client."clients".username]`
* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-clients-password[quarkus.cxf.client."clients".password]`

Here is an example:

.application.properties
[source,properties]
----
include::example$client-server/application.properties[tag=client-basic-auth]
----

=== Accessing WSDL protected by basic authentication

By default, the clients created by {quarkus-cxf-project-name} do not send the `Authorization` header,
unless you set the `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-clients-secure-wsdl-access[quarkus.cxf.client."clients".secure-wsdl-access]` to `true`:

.application.properties
[source,properties]
----
include::example$client-server/application.properties[tag=client-basic-auth-wsdl]
----

== Securing service endpoints

The server-side authentication and authorization is driven by https://quarkus.io/guides/security-overview[Quarkus Security],
especially when it comes to

* https://quarkus.io/guides/security-authentication-mechanisms[Authentication mechanisms]
* https://quarkus.io/guides/security-identity-providers[Identity providers]
* https://quarkus.io/guides/security-authorize-web-endpoints-reference[Role-based access control (RBAC)]

There is a basic example in our https://github.com/quarkiverse/quarkus-cxf/tree/main/integration-tests/client-server[Client and server integration test].
Its key parts are:

* `io.quarkus:quarkus-elytron-security-properties-file` dependency as an Identity provider
* Basic authentication enabled and users with their roles configured in `application.properties`:
+
.application.properties
[source,properties]
----
include::example$client-server/application.properties[tag=users-and-roles]
----
+
* Role-based access control enfoced via `@RolesAllowed` annotation:

.BasicAuthHelloServiceImpl.java
[source,properties]
----
include::example$client-server/BasicAuthHelloServiceImpl.java[]
----
