[[ssl-tls-https]]
= SSL, TLS and HTTPS
:page-aliases: user-guide/ssl.adoc

This section documents various use cases related to SSL, TLS and HTTPS.

[NOTE]
====
The sample code snippets used in this section come from the
{link-quarkus-cxf-source-tree-base}/integration-tests/ws-security-policy[WS-SecurityPolicy integration test]
in the source tree of {quarkus-cxf-project-name}
====


== Client SSL configuration

If your client is going to communicate with a server whose SSL certificate is not trusted by the client's operating system,
then you need to set up a custom trust store for your client.

Tools like `openssl` or Java `keytool` are commonly used for creating and maintaining truststores.

We have examples for both tools in the {quarkus-cxf-project-name} source tree:

* https://github.com/quarkiverse/quarkus-cxf/blob/3.15/integration-tests/ws-security-policy/pom.xml#L185-L520[Create truststore with Java 'keytool' (wrapped by a Maven plugin)]
* https://github.com/quarkiverse/quarkus-cxf/blob/3.15/integration-tests/ws-security-policy/generate-certs.sh[Create truststore with `openssl`]

[TIP]
====
There is a fast and easy way to generate xref:#ssl-certificates-in-tests[certificates for testing].
====

Once you have prepared the trust store, you need to configure your client to use it.

=== Set the client trust store in `application.properties`

This is the easiest way to set the client trust store.
The key role is played by named TLS configurations delivered by {link-quarkus-docs-base}/tls-registry-reference[Quarkus TLS registry]
and by the `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-tls-configuration-name[quarkus.cxf.client."client-name".tls-configuration-name]` property.

[NOTE]
====
{link-quarkus-docs-base}/tls-registry-reference[Quarkus TLS registry] is an extension that centralizes TLS configuration,
making it easier to manage and maintain secure connections across your application.
`io.quarkus:quarkus-tls-registry` is a transitive dependency of `io.quarkiverse.cxf:quarkus-cxf` since {quarkus-cxf-project-name} 3.16.0,
so you do not have to add it manually.
====

Here is an example:

.application.properties
[source,properties]
----
include::example$ws-security-policy/application.properties[tag=client-trust-store]
----

<1> The referenced `client-truststore.pkcs12` file has to be available either in the classpath
    or in the file system.

The new way of configuring TLS is optimized for Vert.x HTTP Client based CXF clients (default since {quarkus-cxf-project-name} 3.16.0).
For those, all client-related options provided by {link-quarkus-docs-base}/tls-registry-reference#configuration-reference[Quarkus TLS registry] are supported.

The named TLS configurations provided by TLS registry can be also used for CXF clients having `http-conduit-factory` set to
`URLConnectionHTTPConduitFactory`.
However, for those, the following TLS options are not supported and using them will lead to an exception at runtime:

* `{link-quarkus-docs-base}/tls-registry-reference#quarkus-tls-registry_quarkus-tls-tls-bucket-name-trust-all[quarkus.tls."tls-bucket-name".trust-all]`
* `{link-quarkus-docs-base}/tls-registry-reference#quarkus-tls-registry_quarkus-tls-tls-bucket-name-hostname-verification-algorithm[quarkus.tls."tls-bucket-name".hostname-verification-algorithm]`
* `{link-quarkus-docs-base}/tls-registry-reference#quarkus-tls-registry_quarkus-tls-tls-bucket-name-reload-period[quarkus.tls."tls-bucket-name".reload-period]`

[NOTE]
====
The xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-trust-store[older way] of configuring the client trust store is still supported, but deprecated since {quarkus-cxf-project-name} 3.16.0:

.application.properties
[source,properties]
----
# Deprecated way of setting the client trust store
quarkus.cxf.client.hello.trust-store-type = pkcs12
quarkus.cxf.client.hello.trust-store = client-truststore.pkcs12
quarkus.cxf.client.hello.trust-store-password = client-truststore-password
----
====


== Server SSL configuration

To make your services available over the HTTPS protocol, you need to set up server keystore in the first place.
The server SSL configuration is driven by Vert.x, the HTTP layer of Quarkus.
{link-quarkus-docs-base}/http-reference#ssl[Quarkus HTTP guide] and {link-quarkus-docs-base}/tls-registry-reference[Quarkus TLS registry reference]
provide the information about the configuration options.

Here is a basic example:

.application.properties
[source,properties]
----
include::example$ws-security-policy/application.properties[tag=server-key-store]
----

[[mtls]]
== Mutual TLS (mTLS) authentication

So far, we have explained the simple or single-sided case
where only the server proves its identity through an SSL certificate
and the client has to be set up to trust that certificate.
Mutual TLS authentication goes by letting also the client prove its identity
using the same means of public key cryptography.

Hence, for the Mutual TLS (mTLS) authentication,
in addition to setting up the server keystore and client truststore as described above,
you need to set up the keystore on the client side and the truststore on the server side.

The tools for creating and maintaining the stores are the same
and the configuration properties to use are pretty much analogous to the ones used in the Simple TLS case.

The {link-quarkus-cxf-source-tree-base}/integration-tests/mtls[mTLS integration test]
in the {quarkus-cxf-project-name} source tree can serve as a good starting point.

The keystores and truststores can be created with
`https://github.com/quarkiverse/quarkus-cxf/blob/3.15/integration-tests/ws-security-policy/generate-certs.sh[openssl]`
(or alternatively with Java https://github.com/quarkiverse/quarkus-cxf/blob/3.15/integration-tests/ws-security-policy/pom.xml#L185-L520[Java `keytool`])

Here is the `application.properties` file:

.application.properties
[source,properties]
----
include::example$mtls/application.properties[tag=mtls]
----

== Enforce SSL through WS-SecurityPolicy

The requirement for the clients to connect through HTTPS can be defined in a policy.

The functionality is provided by `xref:reference/extensions/quarkus-cxf-rt-ws-security.adoc[quarkus-cxf-rt-ws-security]` extension.

Here is an example of a policy file:

.https-policy.xml
[source,xml]
----
include::example$ws-security-policy/https-policy.xml[]
----

The policy has to be referenced from a service endpoint interface (SEI):

.HttpsPolicyHelloService.java
[source,java]
----
include::example$ws-security-policy/HttpsPolicyHelloService.java[]
----

With this setup in place, any request delivered over HTTP will be rejected by the `PolicyVerificationInInterceptor`:

[source,shell]
----
ERROR [org.apa.cxf.ws.pol.PolicyVerificationInInterceptor] Inbound policy verification failed: These policy alternatives can not be satisfied:
 {http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}TransportBinding: TLS is not enabled
 ...
----

[[ssl-certificates-in-tests]]
== SSL certificates for testing

https://github.com/smallrye/smallrye-certificate-generator[SmallRye Certificate Generator] project offers a Junit 5 extension to generate certificates in tests.

First, you need to add the appropriate dependency to your project:

.pom.xml
[source,xml]
----
<dependency>
    <groupId>io.smallrye.certs</groupId>
    <artifactId>smallrye-certificate-generator-junit5</artifactId>
    <scope>test</scope>
</dependency>
----

Then you can use the `@Certificates` annotation in your tests:

.MutualTlsTest.java
[source,java]
----
include::example$mtls/MutualTlsTest.java[tag=smallrye-cert-gen]
    ...
}
----

This will generate the following files (plus the same files in JKS format) suitable for testing xref:#mtls[mutual TLS] authentication:

* `target/classes/localhost-client-keystore.p12` - the client key store
* `target/classes/localhost-keystore.p12` - the server key store
* `target/classes/localhost-server-truststore.p12` - the server trust store
* `target/classes/localhost-truststore.p12` - the client trust store
