= SSL, TLS and HTTPS

This chapter documents various use cases related to SSL, TLS and HTTPS.

NOTE: The sample code snippets used in this section come from the
     https://github.com/quarkiverse/quarkus-cxf/tree/main/integration-tests/ws-security-policy[WS-SecurityPolicy integration test]
     in the source tree of {quarkus-cxf-project-name}


== Client SSL configuration

If your client is going to communicate with a server whose SSL certificate is not trusted by the client's operating system,
then you need to set up a custom trust store for your client.

Tools like `openssl` or Java `keytool` are commonly used for for creating and maintaining truststores.

We have examples for both tools in {quarkus-cxf-project-name} source tree:

* https://github.com/quarkiverse/quarkus-cxf/blob/main/integration-tests/ws-security-policy/pom.xml#L127-L440[Create truststore with Java 'keytool' (wrapped by a Maven plugin)]
* https://github.com/quarkiverse/quarkus-cxf/blob/main/integration-tests/ws-security-policy/generate-certs.sh[Create truststore with `openssl`]

Once you have prepared the trust store, you need to configure your client to use it.

=== Set the client trust store in `application.properties`

This is the easiest way to set the client trust store.
The key role is played by the following properties:

* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-trust-store[quarkus.cxf.client."client-name".trust-store]`
* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-trust-store-type[quarkus.cxf.client."client-name".trust-store-type]`
* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-trust-store-password[quarkus.cxf.client."client-name".trust-store-password]`

Here is an example:

.application.properties
[source,properties]
----
keystore.type = jks <1>
include::example$ws-security-policy/application.properties[tag=client-trust-store]
----

<1> `pkcs12` trust store type is a common alternative to `jks`.
<2> The referenced `client-truststore.jks` file has to be available in `src/main/resources` directory.

== Server SSL configuration

To make your services available over the HTTPS protocol, you need to setup server keystore in the first place.
The server SSL configuration is driven by Vert.x, the HTTP layer of Quarkus.
https://quarkus.io/guides/http-reference#ssl[Quarkus HTTP guide] provides the information about the configuration options.

Here is a basic example:

.application.properties
[source,properties]
----
include::example$ws-security-policy/application.properties[tag=server-key-store]
----

<1> The referenced `localhost.jks` file has to be available in `src/main/resources` directory.

[[mtls]]
== Mutual TLS (mTLS) authentication

So far, we have explained the simple or single-sided case
where only the server proves its identity through an SSL certificate
and the client has to be set up to trust that certificate.
Mutual TLS authentication goes by letting also the client prove its identity
using the same means of public key cryptography.

Hence, for the Mutual TLS (mTLS) authentication,
in addition to setting up the server keystore and client truststore as described above,
you need to setup the keystore on the client side and the truststore on the server side.

The tools for creating and maintaining the stores are the same
and the configuration properties to use are pretty much analogous to the ones used in the Simple TLS case.

The https://github.com/quarkiverse/quarkus-cxf/tree/main/integration-tests/mtl[mTLS integration test]
in the {quarkus-cxf-project-name} source tree can serve as a good starting point.

The keystores and truststores are created with
`https://github.com/quarkiverse/quarkus-cxf/blob/main/integration-tests/mtls/generate-certs.sh[openssl]`
(or alternatively with Java https://github.com/quarkiverse/quarkus-cxf/blob/main/integration-tests/mtls/pom.xml#L109-L377[Java `keytool`])

Here is the `application.properties` file:

.application.properties
[source,properties]
----
# The store type could also be jks
keystore.type = pkcs12

include::example$mtls/application.properties[tag=mtls]
----

== Enforce SSL through WS-SecurityPolicy

The requirement for the clients to connect through HTTPS can be defined in a policy.

The functionality is provided by `xref:reference/extensions/quarkus-cxf-rt-ws-security.adoc[quarkus-cxf-rt-ws-security]` extension.

Here is an example of a policy file:

.https-policy.xml
[source,properties]
----
include::example$ws-security-policy/https-policy.xml[]
----

The policy has to be referenced from a service endpoint interface (SEI):

.HttpsPolicyHelloService.java
[source,java]
----
include::example$ws-security-policy/HttpsPolicyHelloService.java[]
----

With this setup in place, any request delivered over HTTP will be rejected by the `PolicyVerificationInInterceptor`:

[source,shell]
----
ERROR [org.apa.cxf.ws.pol.PolicyVerificationInInterceptor] Inbound policy verification failed: These policy alternatives can not be satisfied:
 {http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702}TransportBinding: TLS is not enabled
 ...
----
