package io.quarkiverse.cxf.deployment.test.client.model;

import java.util.concurrent.Future;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.AsyncHandler;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.Response;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-11-15T12:48:45.542+01:00
 * Generated source version: 4.0.5
 *
 */
@WebService(targetNamespace = "http://test.deployment.cxf.quarkiverse.io/", name = "HelloService")
@XmlSeeAlso({ ObjectFactory.class })
public interface HelloService {

    @WebMethod(operationName = "hello")
    @RequestWrapper(localName = "hello", targetNamespace = "http://test.deployment.cxf.quarkiverse.io/", className = "io.quarkiverse.cxf.deployment.test.client.model.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://test.deployment.cxf.quarkiverse.io/", className = "io.quarkiverse.cxf.deployment.test.client.model.HelloResponse")
    public Response<io.quarkiverse.cxf.deployment.test.client.model.HelloResponse> helloAsync(

            @WebParam(name = "arg0", targetNamespace = "") java.lang.String arg0);

    @WebMethod(operationName = "hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://test.deployment.cxf.quarkiverse.io/", className = "io.quarkiverse.cxf.deployment.test.client.model.HelloResponse")
    @RequestWrapper(localName = "hello", targetNamespace = "http://test.deployment.cxf.quarkiverse.io/", className = "io.quarkiverse.cxf.deployment.test.client.model.Hello")
    public Future<?> helloAsync(

            @WebParam(name = "arg0", targetNamespace = "") java.lang.String arg0,
            @WebParam(name = "asyncHandler", targetNamespace = "") AsyncHandler<io.quarkiverse.cxf.deployment.test.client.model.HelloResponse> asyncHandler);

    @WebMethod
    @RequestWrapper(localName = "hello", targetNamespace = "http://test.deployment.cxf.quarkiverse.io/", className = "io.quarkiverse.cxf.deployment.test.client.model.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://test.deployment.cxf.quarkiverse.io/", className = "io.quarkiverse.cxf.deployment.test.client.model.HelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String hello(

            @WebParam(name = "arg0", targetNamespace = "") java.lang.String arg0);
}
