name: build-and-run-jvm-tests
description: |
   Build the project and run JVM tests. 
   Prerequisites: 
     * java must be installed'

inputs:
  run-native-tests:
    description: "If true, the native tests will be run in addition to JVM tests; otherwise only JVM tests will be run"
    default: 'false'

runs:
  using: 'composite'
  steps:

    - name: Ensure mvn cq:sync-versions -N causes no changes
      shell: bash
      run: |
        ./mvnw cq:sync-versions -Dcq.simpleElementWhitespace=AUTODETECT_PREFER_SPACE -N -ntp
        [[ -z $(git status --porcelain | grep -v antora.yml) ]] || { echo 'There are uncommitted changes'; git status; git diff; exit 1; }

    - name: mvn -B formatter:validate install
      shell: bash
      run: ./mvnw -B formatter:validate install -fae -ntp ${{ inputs.run-native-tests == 'true' && '-Pnative -Dquarkus.native.container-build' || '' }}

    # Same as the previous but only JVM tests and different default ConduitFactory
    - name: QUARKUS_CXF_DEFAULT_HTTP_CONDUIT_FACTORY=URLConnectionHTTPConduitFactory mvn -B test
      shell: bash
      env: 
        QUARKUS_CXF_DEFAULT_HTTP_CONDUIT_FACTORY: URLConnectionHTTPConduitFactory
      run: ./mvnw -B clean install -fae -ntp ${{ inputs.run-native-tests == 'true' && '-Pnative -Dquarkus.native.container-build' || '' }}

    - name: 'Upload generated Antora docs site'
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: docs/target/site

    - name: Fail if there are uncommitted changes
      shell: bash
      run: |
        [[ -z $(git status --porcelain | grep -v antora.yml) ]] || { echo 'There are uncommitted changes'; git status; git diff; exit 1; }

    - name: Tar Maven Repo
      shell: bash
      run: |
        tar -czf ${{ runner.temp }}/maven-repo.tgz -C ~ .m2/repository
        # Avoid caching our own artifacts
        rm -Rf ~/.m2/repository/io/quarkiverse/cxf
    - name: Persist Maven Repo
      uses: actions/upload-artifact@v4
      with:
        name: maven-repo
        path: ${{ runner.temp }}/maven-repo.tgz
        retention-days: 1
