This extension wraps the CXF `org.apache.cxf:cxf-rt-features-logging` artifact
thus providing the `org.apache.cxf.ext.logging.LoggingFeature` class.

=== Configuring through configuration properties

Since {quarkus-cxf-project-name} 2.5.0, the `LoggingFeature` can be configured and attached to a client or a service
endpoint declaratively by setting the appropriate options in `application.properties`:

.application.properties
[source,properties,subs=attributes+]
----
# For a service:
quarkus.cxf.endpoint."/hello".logging.enabled = true
quarkus.cxf.endpoint."/hello".logging.pretty = true
# For a client:
quarkus.cxf.client.hello.logging.enabled = true
quarkus.cxf.client.hello.logging.pretty = true
----

All logging configuration options are listed xref:#quarkus-cxf-rt-features-logging-configuration[below].

=== Alternative ways of adding a `LoggingFeature` to a client or service

To attach an instance with default settings, you can do one of the following:

1. In `application.properties`:
+
[source,properties,subs=attributes+]
----
# For a service:
quarkus.cxf.endpoint."/hello".features=org.apache.cxf.ext.logging.LoggingFeature
# For a client:
quarkus.cxf.client."myClient".features=org.apache.cxf.ext.logging.LoggingFeature
----
+
TIP: There is an example in xref:user-guide/first-soap-web-service.adoc#logging-feature[Your first SOAP Web service] chapter of the User guide.
+
or alternatively
+
2. Use the `@Features` annotation of CXF:
+
[source,java]
----
@org.apache.cxf.feature.Features (features = {"org.apache.cxf.ext.logging.LoggingFeature"})
@WebService(endpointInterface = "org.acme.SayHi", targetNamespace = "uri:org.acme")
public class SayHiImplementation implements SayHi {
   public long sayHi(long arg) {
       return arg;
   }
   //...
}
----

==== Producing a custom `LoggingFeature` bean

If you need some custom logic to setup the `LoggingFeature`, you can produce a named `LoggingFeature` bean:

[source,java,subs="attributes"]
----
import org.apache.cxf.ext.logging.LoggingFeature;
import {javaxOrJakartaPackagePrefix}.enterprise.context.ApplicationScoped;
import {javaxOrJakartaPackagePrefix}.enterprise.inject.Produces;

class Producers {

    @Produces
    @ApplicationScoped
    @Named("limitedLoggingFeature") // "limitedLoggingFeature" is redundant if the name of the method is the same
    LoggingFeature limitedLoggingFeature() {
        LoggingFeature loggingFeature = new LoggingFeature();
        loggingFeature.setPrettyLogging(true);
        loggingFeature.setLimit(1024);
        return loggingFeature;
    }
}
----

Then you can refer to it by its name prefixed with `#` in `application.properties`:

[source,properties,subs=attributes+]
----
# For a service:
quarkus.cxf.endpoint."/hello".features = #limitedLoggingFeature
# For a client:
quarkus.cxf.client.hello.features = #limitedLoggingFeature
----

