The CXF framework's WS-Security (WSS) implementation is based on https://ws.apache.org/wss4j/user_guide.html[WSS4J].
It can be activated in two ways:

* By using WS-SecurityPolicy
* By adding WSS4J interceptors to your clients and service endpoints.

WS-SecurityPolicy is preferable because in that way, the security requirements become a part of the WSDL contract.
That in turn greatly simplifies not only the implementation of clients and service endpoints
but also the interoperability between vendors.

Nevertheless, if you leverage WS-SecurityPolicy, CXF sets up the WSS4J interceptors under the hood for you.

We won't explain the manual approach with WSS4J interceptors in detail here,
but you can still refer to our https://github.com/quarkiverse/quarkus-cxf/tree/main/integration-tests/ws-security[WS-Security integration test] as an example.

=== WS-Security via WS-SecurityPolicy

[TIP]
====
The sample code snippets used in this section come from the
https://github.com/quarkiverse/quarkus-cxf/tree/main/integration-tests/ws-security-policy[WS-SecurityPolicy integration test]
in the source tree of {quarkus-cxf-project-name}
====

Let's say our aim is to ensure that the communication between the client and service is confidential (through encryption)
and that the message has not been tampered with (through digital signatures).
We also want to assure that the clients are who they claim to be by authenticating themselves by X.509 certificates.

We can express all these requirements in a single {link-quarkus-cxf-source-tree-base}/integration-tests/ws-security-policy/src/main/resources/encrypt-sign-policy.xml[WS-SecurityPolicy document]:

.encrypt-sign-policy.xml
[source,xml]
----
include::example$ws-security-policy/encrypt-sign-policy.xml[]
----

<1> `AsymmetricBinding` specifies the use of asymmetric (public/private key) cryptography for securing the communication between two parties
<2> `InitiatorToken` indicates that the initiator (sender) of the message will use an X.509 certificate token that must always be provided to the recipient.
<3> `SignedParts` specifies which parts of the SOAP message must be signed to ensure their integrity.
<4> `EncryptedParts` specifies the parts of the SOAP message that must be encrypted to ensure their confidentiality.

We set this policy on the Service Endpoint Interface (SEI)
`{link-quarkus-cxf-source-tree-base}/integration-tests/ws-security-policy/src/main/java/io/quarkiverse/cxf/it/security/policy/EncryptSignPolicyHelloService.java#L11[EncryptSignPolicyHelloService]`
using `@org.apache.cxf.annotations.Policy` annotation:

.EncryptSignPolicyHelloService.java
[source,java]
----
include::example$ws-security-policy/EncryptSignPolicyHelloService.java[tag=quarkus-cxf-rt-ws-security.adoc]
...
}
----

On the first sight, setting the policy on the SEI should suffice to enforce it on both the service
and all clients generated from the SEI or from the WSDL served by the service.
However, that's not all.
Security keys, usernames, passwords and other kinds of confidental information cannot be exposed in a public policy.

Those have to be set in the configuration. Let's do it for the service first:

.application.properties
[source,properties]
----
include::example$ws-security-policy/application.properties[tag=quarkus-cxf-rt-ws-security.adoc-service]
----

Similar setup is necessary on the client side:

.application.properties
[source,properties]
----
include::example$ws-security-policy/application.properties[tag=quarkus-cxf-rt-ws-security.adoc-client]
----

To inspect the flow of the messages, you can execute the `EncryptSignPolicyTest` as follows:

[source,shell]
----
# Clone the repository
$ git clone https://github.com/quarkiverse/quarkus-cxf.git -o upstream
$ cd quarkus-cxf
# Build the whole source tree
$ mvn clean install -DskipTests -Dquarkus.build.skip
# Run the test
$ cd integration-tests/ws-security-policy
$ mvn clean test -Dtest=EncryptSignPolicyTest
----

You should see some messages containing `Signature` elements and encrypted bodies in the console output.
