The CXF framework's WS-Security implementation is based on https://ws.apache.org/wss4j/user_guide.html[WSS4J]. The example below shows how to integrate with WSS4J using interceptors.

NOTE: Currently, only the programmatic WSS4JInterceptors are supported. Actions like `Timestamp`, `UsernameToken`, `Signature`, `Encryption`, etc., can be applied to the interceptors by passing the appropriate configuration properties.

[[ws-security-service]]
=== A SOAP Service with WS-Security

Add the `WSS4JInInterceptor` to `in-interceptors` of your web service in `application.properties`:

[source,properties]
----
include::example$ws-security-server/application.properties[tag=quarkus-cxf-rt-ws-security.adoc]
----

NOTE: The sample code snippets used in this section come from the
     https://github.com/quarkiverse/quarkus-cxf/tree/main/integration-tests/ws-security-server[WS-Security server integration test]
     in the source tree of {quarkus-cxf-project-name}

Then you can configure your `WSS4JInInterceptor` using CDI like the following:

[source,java]
----
include::example$ws-security-server/WSS4JInInterceptorProducer.java[tag=quarkus-cxf-rt-ws-security.adoc]
----

[[ws-security-client]]
== A SOAP client using WS-Security

The corresponding client implementation would be slightly different:
we will use `WSS4JOutInterceptor` and `out-interceptors` in `application.properties`:

[source,properties]
----
include::example$ws-security-client/application.properties[tag=quarkus-cxf-rt-ws-security.adoc]
----

NOTE: The sample code snippets used in this section come from the
     https://github.com/quarkiverse/quarkus-cxf/tree/main/integration-tests/ws-security-client[WS-Security client integration test]
     in the source tree of {quarkus-cxf-project-name}

Then producing the `WSS4JOutInterceptor` could look like the following.

[source,java]
----
include::example$ws-security-client/WSS4JOutInterceptorProducer.java[tag=quarkus-cxf-rt-ws-security.adoc]
----

Please refer to https://cxf.apache.org/docs/ws-security.html[WS-Security] and https://ws.apache.org/wss4j/user_guide.html[WSS4J] documentation for details.
