= Quarkus CXF client tests

These are pure client tests - i.e. there are intentionally no services implemented in the test application.
All clients access services running in containers.

== Maintenenance notes

=== `CalculatorService.wsdl`

`src/main/cxf-codegen-resources/wsdl/CalculatorService.wsdl` is a static copy of the WSDL served by the testing container.
It is used solely by `cxf-codegen-plugin`.
It would be too complicated to start the container before running the plugin, so we rather keep the static copy.

There is `io.quarkiverse.cxf.client.it.CxfClientTest.wsdlUpToDate()` to ensure that it is up to date.

To update `CalculatorService.wsdl` manually, first start the container

[shource,shell]
----
$ docker pull quay.io/l2x6/calculator-ws:1.0
$ docker run -p 8080:8080 quay.io/l2x6/calculator-ws:1.0
----

And then overwrite the existing file with the new content from the container:

[shource,shell]
----
curl http://localhost:8080/calculator-ws/CalculatorService?wsdl --output src/main/cxf-codegen-resources/wsdl/CalculatorService.wsdl
----

[[soak]]
== `CxfClientTest.soakRequestScopedHttpClient()` and `CxfClientTest.soakRequestScopedUrlConnectionClient()`

The number of iterations performed by these tests can be set via

[source,shell]
----
$ export QUARKUS_CXF_CLIENT_SOAK_ITERATIONS=100000
$ mvn clean test -Dtest=CxfClientTest#soakRequestScopedHttpClient
$ mvn clean test -Dtest=CxfClientTest#soakRequestScopedUrlConnectionClient
----

The hard-coded default of 300 is intentionally low to make the test pass on Quarkus Platform CI.
Higher values are more likely to uncover resource leaks.