= Quarkus CXF client tests

These are pure client tests - i.e. there are intentionally no services implemented in the test application.
All clients access services running in containers.

== Maintenenance notes

=== `CalculatorService.wsdl`

`src/main/cxf-codegen-resources/wsdl/CalculatorService.wsdl` is a static copy of the WSDL served by the testing container.
It is used solely by `cxf-codegen-plugin`.
It would be too complicated to start the container before running the plugin, so we rather keep the static copy.

There is `io.quarkiverse.cxf.client.it.CxfClientTest.wsdlUpToDate()` to ensure that it is up to date.

To update `CalculatorService.wsdl` manually, first start the container

[shource,shell]
----
$ docker pull quay.io/l2x6/calculator-ws:1.0
$ docker run -p 8080:8080 quay.io/l2x6/calculator-ws:1.0
----

And then overwrite the existing file with the new content from the container:

[shource,shell]
----
curl http://localhost:8080/calculator-ws/CalculatorService?wsdl --output src/main/cxf-codegen-resources/wsdl/CalculatorService.wsdl
----

[[soak]]
== `CxfClientTest.soakRequestScopedVertxHttpClient()` and `CxfClientTest.soakRequestScopedUrlConnectionClient()`

These tests are sensitive to some parameters, such as the number of iterations and acceptable deviation of number of
threads.

[source,shell]
----
$ export QUARKUS_CXF_CLIENT_SOAK_ITERATIONS=300 # 300 is default
$ export QUARKUS_CXF_CLIENT_SOAK_ACCEPTABLE_THREAD_COUNT_DEVIATION=5 # 5 is default
$ mvn clean test -Dtest=CxfClientTest#soakRequestScopedVertxHttpClient
$ mvn clean test -Dtest=CxfClientTest#soakRequestScopedHttpClient
$ mvn clean test -Dtest=CxfClientTest#soakRequestScopedUrlConnectionClient
----

The hard-coded default `QUARKUS_CXF_CLIENT_SOAK_ITERATIONS=300` should be enough since Quarkus CXF 3.8.1
when we started watching the number of active threads after the 10th iteration as follows:

* The the number of active threads after the 10th iteration is recorded.
* After all subsequent iterations, the current number of active threads is compared with the recorded value.
* The test fails if the current value is higher than the recorded value plus
  `QUARKUS_CXF_CLIENT_SOAK_ACCEPTABLE_THREAD_COUNT_DEVIATION`.
