[[generate-java-from-wsdl]]
= Generate the Model classes from WSDL

`quarkus-cxf` extension supports generating Java classes from WSDL during Quarkus code generation phase.

[NOTE]
.Code examples
====
The code snippets shown in this section come from the
{link-quarkus-cxf-source-tree-base}/integration-tests/client[client integration test]
in the source tree of {quarkus-cxf-project-name}.
You may want to check it as an executable example.
====

You need to set up a couple of things for CXF code generation to work:

* Have `io.quarkiverse.cxf:quarkus-cxf` dependency in your project
* For Maven projects, the `generate-code` goal needs to be present in the configuration of `quarkus-maven-plugin`:
+
.pom.xml
[source,xml]
----
include::example$calculator-client/pom.xml[tag=first-soap-client.adoc-quarkus-maven-plugin]
----
+
* For Gradle projects no additional configurarion of `io.quarkus` plugin is needed
* Put your WSDL files under `src/main/resources` or `src/test/resources` or any subdirectory thereof.
* Your WSDL file names must end with `.wsdl`
* Set `quarkus.cxf.codegen.wsdl2java.includes`
  xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-codegen-wsdl2java-includes[configuration property]
  to a pattern matching the WSDL files you wish to process.
  If you want to process all WSDL files under `src/main/resources/wsdl` or `src/test/resources/wsdl`, set it as follows:
+
.application.properties
[source,properties]
----
quarkus.cxf.codegen.wsdl2java.includes = wsdl/*.wsdl
----

This will generate Java classes in `target/generated-sources/wsdl2java` or
`target/generated-test-sources/wsdl2java` directory.
They will be automatically picked by the compiler plugin there.
Hence we are free to refer to them from our application or test code.

[NOTE]
====
Note that `quarkus-cxf` code generation uses the https://cxf.apache.org/docs/wsdl-to-java.html[wsdl2Java] utility
from CXF under the hood. `wsdl2Java` is called separately for each WSDL file selected by `includes` and `excludes`.
====

Passing custom parameters to `wsdl2java` is possible through various
xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-codegen-wsdl2java-enabled[`quarkus.cxf.codegen.wsdl2java.*`]
configuration parameters.

If you need different parameters for each WSDL file, you may want to define a separate named parameter set for
each one of them. Here is an example:

.application.properties
[source,properties]
----
# Parameters for foo.wsdl
quarkus.cxf.codegen.wsdl2java.foo-params.includes = wsdl/foo.wsdl
quarkus.cxf.codegen.wsdl2java.foo-params.wsdl-location = wsdl/foo.wsdl
# Parameters for bar.wsdl
quarkus.cxf.codegen.wsdl2java.bar-params.includes = wsdl/bar.wsdl
quarkus.cxf.codegen.wsdl2java.bar-params.wsdl-location = wsdl/bar.wsdl
quarkus.cxf.codegen.wsdl2java.bar-params.xjc = ts
----

[[generate-java-from-wsdl-customize-the-java-model-classes]]
== Customize the Java model classes

As we mentioned earlier, the `io.quarkiverse.cxf:quarkus-cxf` extension embeds the `wsdl2java` tool
and it is invoked during Quarkus code generation phase.

The way how `wsdl2java` shapes the Java model classes can be customized in two main ways:

1. xref:#generate-java-from-wsdl-jaxb-and-or-jaxws-binding-files[JAXB and/or JAXWS binding files]
2. xref:#generate-java-from-wsdl-xjc-plugins[XJC Plugins]

[[generate-java-from-wsdl-jaxb-and-or-jaxws-binding-files]]
=== JAXB and/or JAXWS binding files

JAXB and/or JAXWS Binding files are two flavors of the same:
they both exist for the purpose of enhancing or adjusting some sort of a contract before the Java classes are generated out of it.

While JAXB Binding files are applied to XML Schema (XSD) documents,
the JAXWS Binding files are applied to WSDL documents.

Both JAXB and JAXWS Binding files are passed to `wsdl2java` via
xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-codegen-wsdl2java-bindings[quarkus.cxf.codegen.wsdl2java.bindings]
or xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-codegen-wsdl2java-named-parameter-sets-bindings[quarkus.cxf.codegen.wsdl2java."named-parameter-sets".bindings]
options.

=== JAXB Binding files

If you ask, why XML Schemas matter in the context of `wsdl2java` then the answer is
that WSDLs either embed inline XML Schemas or they incude external XML Schema documents.
You may customize those using JAXB Binding files.

JAXB Binding file names typically end with `.xjb` but `.xml` will work too.

The format of JAXB Binding files is governed by the `https://jakarta.ee/xml/ns/jaxb` namespace
and https://jakarta.ee/xml/ns/jaxb/bindingschema_3_0.xsd[Jakarta XML Binding 3.0 Schema].

Here is an example that instructs the JAXB schema binding compiler (XJC) to render each XML attribute
having type `xs:dateTime` as `java.time.OffsetDateTime`:

.global-jaxb-bindings.xml
[source,xml]
----
include::example$wsdl2java/global-jaxb-bindings.xml[]
----

=== JAXWS Binding files

The format of JAXWS Binding files is governed by the `https://jakarta.ee/xml/ns/jaxws` namespace
and https://jakarta.ee/xml/ns/jaxb/bindingschema_3_0.xsd[XML Schema for the Jakarta XML Web Services WSDL customization descriptor].

Check the example in the
xref:user-guide/advanced-client-topics/asynchronous-client.adoc#asynchronous-client-generate-async-methods[Asynchronous client] guide.

[[generate-java-from-wsdl-xjc-plugins]]
== XJC plugins

`wsdl2java` delegates the process of generating Java classes from XML Schemas to JAXB schema binding compiler (XJC).
XJC has a pluggable architecture and a number of plugins exist that can customize the rendering in various ways.

To use those plugins you need to:

* Add an extension embedding the plugins to your project's dependencies. {quarkus-cxf-project-name} currently offers two such extensions:
** `xref:reference/extensions/quarkus-cxf-xjc-plugins.adoc[io.quarkiverse.cxf:quarkus-cxf-xjc-plugins]`
** `xref:reference/extensions/quarkus-cxf-jaxb-plugins.adoc[io.quarkiverse.cxf:quarkus-cxf-jaxb-plugins]`
* Activate the desired plugin via
  `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-codegen-wsdl2java-xjc[quarkus.cxf.codegen.wsdl2java.xjc]`
  or `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-codegen-wsdl2java-named-parameter-sets-xjc[quarkus.cxf.codegen.wsdl2java."named-parameter-sets".xjc]`
  configuration option.
  Check `xref:reference/extensions/quarkus-cxf-xjc-plugins.adoc[quarkus-cxf-xjc-plugins]`
  and `xref:reference/extensions/quarkus-cxf-jaxb-plugins.adoc[quarkus-cxf-jaxb-plugins]`
  for the list of available plugins.
