[[dynamic-client-configuration]]
= Dynamic client configuration

Sometimes you need to reconfigure the client after the application has
xref:user-guide/advanced-client-topics/programmatic-client-configuration-at-startup.adoc#programmatic-client-configuration-at-startup[been started],
or even before every request.
This might be the case, if, for example, each request needs to be sent to a different remote URL.

CXF offers an API to set the URL of the remote endpoint.
However using that API on a client instance that may be accessed from other threads can lead to race conditions.

== Preventing concurrent access to a CXF client

If your client is used as a part of serving an external request,
you can inject the client into a xref:user-guide/advanced-client-topics/cdi-scope-of-cxfclient.adoc#cdi-scope-of-cxfclient[`@RequestScoped` bean].
Then every request will be served by a fresh client instance and you can configure it safely.

For example, this solution is applicable when your client is called from a REST-handler method (see below)
or from a `@WebMethod` that are serving external requests.

[source,java]
----
include::example$calculator-client/DynamicClientConfigRestResource.java[]
----
