= {quarkus-cxf-project-name} 3.19.0 release notes

== Important dependency upgrades

* Quarkus 3.18.x -> 3.19.0 - https://quarkus.io/blog/quarkus-3-19-1-released/[release notes]

== New features

=== https://github.com/quarkiverse/quarkus-cxf/issues/1680[#1680] Introduce `quarkus.cxf.client.tls-configuration-name` to set TLS options for all CXF clients

Before {quarkus-cxf-project-name} 3.19.0, it was only possible to configure trust stores and key stores per CXF client via
`xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-tls-configuration-name[quarkus.cxf.client."client-name".tls-configuration-name]`
or (now deprecated)
`xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-key-store[quarkus.cxf.client."client-name".key-store*]`
and
`xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-trust-store[quarkus.cxf.client."client-name".trust-store*]` options.

The configuration might have got too verbose in case there were multiple clients.

Since {quarkus-cxf-project-name} 3.19.0, it is possible to set the trust stores and key stores for all clients using the
`xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-tls-configuration-name[quarkus.cxf.client.tls-configuration-name]` option.


== Known issues

=== https://github.com/quarkusio/quarkus/issues/46368[quarkus#46368] `javax.net.ssl` TLS configuration does not work in native mode

This issue exists in `io.quarkus:quarkus-tls-registry` 3.19.0  and will be fixed in version 3.19.1 due on Wednesday Feb. 26, 2025.

With {quarkus-cxf-project-name} 3.19.0, all CXF clients in native mode are impacted
which rely on the default value `javax.net.ssl` of configuration property
`xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-tls-configuration-name[quarkus.cxf.client.tls-configuration-name]`.

There are several options to workaround the issue:

* Start the native executable with `-Djavax.net.ssl.trustStore=$JAVA_HOME/lib/security/cacerts -Djavax.net.ssl.trustStorePassword=changeit`
* Set a custom trust store on `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-tls-configuration-name[quarkus.cxf.client.tls-configuration-name]`:
+
.application.properties
[source,properties]
----
quarkus.tls.localCacertsFile.trust-store.p12.path = ${JAVA_HOME}/lib/security/cacerts
quarkus.tls.localCacertsFile.trust-store.p12.password = changeit
quarkus.cxf.client.tls-configuration-name = localCacertsFile
----

== Bugfixes

=== https://github.com/quarkiverse/quarkus-cxf/issues/1697[#1697] Native build fails when using `quarkus-cxf-integration-tracing-opentelemetry` and `quarkus-jdbc-oracle`

Before {quarkus-cxf-project-name} 3.19.0, combining `quarkus-jdbc-oracle` with `quarkus-cxf-integration-tracing-opentelemetry`
or `quarkus-cxf-rt-ws-rm` in a single application resulted in an error during the build of native image as follows:

[source]
----
org.graalvm.compiler.debug.GraalError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException:
Detected a MBean server in the image heap. This is currently not supported, but could be changed in the future.
Management beans are registered in many global caches that would need to be cleared and properly re-built at image build time.
Class of disallowed object: com.sun.jmx.mbeanserver.JmxMBeanServer
----

We have fixed this in {quarkus-cxf-project-name} 3.19.0, but note that JMX features are not supported in native mode.


== Deprecations

=== https://github.com/quarkiverse/quarkus-cxf/issues/1632[#1632] `io.quarkiverse.cxf:quarkus-cxf-rt-transports-http-hc5` deprecated

The `io.quarkiverse.cxf:quarkus-cxf-rt-transports-http-hc5` extension is deprecated since {quarkus-cxf-project-name} 3.19.0
and it is scheduled for removal in 3.21.0.
Use the xref:user-guide/advanced-client-topics/asynchronous-client.adoc[asynchronous mode of `VertxHttpClientHTTPConduit`] instead.

This is a part of our efforts to support only a single HTTP Conduit based on Vert.x HttpClient in the future.

We deprecated the `HttpClientHTTPConduitFactory` value of
`xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-http-conduit-factory[quarkus.cxf.http-conduit-factory]`
and `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-http-conduit-factory[quarkus.cxf.client."client-name".http-conduit-factory]`
for the same reason in the
xref:release-notes/3.18.0.adoc#issue_1633_httpclienthttpconduitfactory_value_deprecated[previous release].

== Documentation improvements

* xref:/reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-logging-limit[Document that `quarkus.cxf.logging.limit = -1` means no limit]
* Add xref:user-guide/configuration.adoc#declarative-vs-programmatic-configuration[Declarative vs. programmatic configuration] section
* Do not mention the deprecated `quarkus-cxf-rt-features-logging` extension in the xref:user-guide/first-soap-web-service.adoc#logging-feature[First SOAP service] guide
* xref:user-guide/payload-logging.adoc#per-client-or-service-endpoind-payload-logging[Explain `*.logging.enabled = pretty`] and use it in examples
* Document the xref:user-guide/advanced-client-topics/asynchronous-client.adoc[Asynchronous client] properly

== Full changelog

https://github.com/quarkiverse/quarkus-cxf/compare/3.18.1+++...+++3.19.0
