= Aggregated {quarkus-cxf-project-name} release notes 3.15.3 LTS -> 3.20.2 LTS

This document may help when upgrading from the 3.15 LTS stream to 3.20 LTS stream.

== Important dependency upgrades

* Quarkus 3.15.x -> 3.20.x
** https://quarkus.io/blog/quarkus-3-16-1-released/[Quarkus 3.16.0/3.16.1 release notes]
** https://quarkus.io/blog/quarkus-3-17-0-released/[Quarkus 3.17.0 release notes]
** https://quarkus.io/blog/quarkus-3-17-2-released/[Quarkus 3.17.1/3.17.2 release notes]
** https://quarkus.io/blog/quarkus-3-17-3-released/[Quarkus 3.17.3 release notes]
** https://quarkus.io/blog/quarkus-3-18-1-released/[Quarkus 3.18.0/3.18.1 release notes]
** https://quarkus.io/blog/quarkus-3-19-1-released/[Quarkus 3.19.0/3.19.1 release notes]
** https://quarkus.io/blog/quarkus-3-20-0-released/[Quarkus 3.20.0 release notes]

* CXF 4.0.5 -> 4.1.1 - https://cxf.apache.org/download.html[release notes], link:https://github.com/apache/cxf/compare/cxf-4.0.5+++...+++cxf-4.1.1[changelog]

* Santuario XML Security 3.0.4 -> 4.0.4 - https://github.com/apache/santuario-xml-security-java/compare/xmlsec-3.0.4+++...+++xmlsec-4.0.4[changelog]
* WSS4J 3.0.3 -> 4.0.0
** https://github.com/apache/ws-wss4j/releases/tag/wss4j-3.0.4[WSS4J 3.0.4 release notes], https://github.com/apache/ws-wss4j/compare/wss4j-3.0.3+++...+++wss4j-3.0.4[changelog]
** https://github.com/apache/ws-wss4j/releases/tag/wss4j-4.0.0[WSS4J 4.0.0 release notes], https://github.com/apache/ws-wss4j/compare/wss4j-3.0.4+++...+++wss4j-4.0.0[changelog]

== New and noteworthy in {quarkus-cxf-project-name}

=== https://github.com/quarkiverse/quarkus-cxf/issues/1486[#1486] TLS Registry support

{link-quarkus-docs-base}/tls-registry-reference[Quarkus TLS registry] is an extension provided by Quarkus that centralizes the TLS configuration,
making it easier to manage and maintain secure connections across your application.

[NOTE]
====
`io.quarkus:quarkus-tls-registry` is a transitive dependency of `io.quarkiverse.cxf:quarkus-cxf` since {quarkus-cxf-project-name} 3.16.0,
so you do not have to add it manually.
====

Quarkus TLS registry is the new recommended way of configuring trust stores, keystores and other TLS/SSL related settings in {quarkus-cxf-project-name} 3.16.0+:

.application.properties
[source,properties]
----
include::example$ws-security-policy/application.properties[tag=client-trust-store]
----

<1> The referenced `client-truststore.pkcs12` file has to be available either in the classpath
    or in the file system.

All client-related options provided by {link-quarkus-docs-base}/tls-registry-reference#configuration-reference[Quarkus TLS registry] are supported for Vert.x based CXF clients.

==== Limitations with other clients
The named TLS configurations provided by TLS registry can be also used for CXF clients having `http-conduit-factory` set to
`URLConnectionHTTPConduitFactory`, `HttpClientHTTPConduitFactory` or with
Async CXF clients on top of Apache HttpClient 5.
However, in those cases, the following TLS options are not supported and using them will lead to an exception at runtime:

* `{link-quarkus-docs-base}/tls-registry-reference#quarkus-tls-registry_quarkus-tls-tls-bucket-name-trust-all[quarkus.tls."tls-bucket-name".trust-all]`
* `{link-quarkus-docs-base}/tls-registry-reference#quarkus-tls-registry_quarkus-tls-tls-bucket-name-hostname-verification-algorithm[quarkus.tls."tls-bucket-name".hostname-verification-algorithm]`
* `{link-quarkus-docs-base}/tls-registry-reference#quarkus-tls-registry_quarkus-tls-tls-bucket-name-reload-period[quarkus.tls."tls-bucket-name".reload-period]`

==== Deprecated stores
The xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-trust-store[older way] of configuring client trust stores and key stores is still supported, but deprecated since {quarkus-cxf-project-name} 3.16.0:

.application.properties
[source,properties]
----
# Deprecated way of setting the client trust store
quarkus.cxf.client.hello.trust-store-type = pkcs12
quarkus.cxf.client.hello.trust-store = client-truststore.pkcs12
quarkus.cxf.client.hello.trust-store-password = client-truststore-password
----


=== Vert.x HttpClient based HTTP Conduit is the new default

Vert.x HttpClient based HTTP Conduit was xref:release-notes/3.13.0.adoc#vert-x-httpclient-based-http-conduit-default[introduced] in {quarkus-cxf-project-name} 3.13.0.
Its usage was optional through setting the `VertxHttpClientHTTPConduitFactory` on either of the options
`xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-http-conduit-factory[quarkus.cxf.client."client-name".http-conduit-factory]` or
`xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-http-conduit-factory[quarkus.cxf.http-conduit-factory]`:

.application.properties
[source,properties]
----
# Before Quarkus CXF 3.16.0, VertxHttpClientHTTPConduitFactory had to be set explicitly
# Set the HTTPConduitFactory per-client
quarkus.cxf.client."client-name".http-conduit-factory = VertxHttpClientHTTPConduitFactory
# Set the HTTPConduitFactory globally
quarkus.cxf.http-conduit-factory = VertxHttpClientHTTPConduitFactory
----

Since then, it went through some improvements and testing so that we are now confident to make it default.

The main motivations for using Vert.x HttpClient based HTTP Conduit as a default are as follows:

* Support for HTTP/2
* Seamless integration with Quarkus, especially in the areas of worker thread poolling and SSL/TLS configuration.


==== Force the old default

Before this change, the effective default was `URLConnectionHTTPConduitFactory`.
It is still supported and tested regularly.

You can get back to the old default in any one of three ways:

. Set the `QUARKUS_CXF_DEFAULT_HTTP_CONDUIT_FACTORY` environment variable to `URLConnectionHTTPConduitFactory`
. Set the global xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-http-conduit-factory[quarkus.cxf.http-conduit-factory] option to `URLConnectionHTTPConduitFactory`
. Set the per client xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-http-conduit-factory[quarkus.cxf.client."client-name".http-conduit-factory] option to `URLConnectionHTTPConduitFactory`

==== Hostname verifiers not supported in combination with `VertxHttpClientHTTPConduitFactory`

Since {quarkus-cxf-project-name} 3.16.0, setting
`xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-hostname-verifier[quarkus.cxf.client."client-name".hostname-verifier]`
together with using the default `VertxHttpClientHTTPConduitFactory` leads to an exception at runtime.

The `AllowAllHostnameVerifier` value of that option can be replaced by using a
xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-tls-configuration-name[named TLS configuration]
with `{link-quarkus-docs-base}/tls-registry-reference#trusting-all-certificates-and-hostname-verification[hostname-verification-algorithm]`
set to `NONE`.

Here is an example: if your configuration before {quarkus-cxf-project-name} 3.16.0 was as follows

.application.properties
[source,properties]
----
# A configuration that worked before Quarkus CXF 3.16.0
quarkus.cxf.client.helloAllowAll.client-endpoint-url = https://localhost:8444/services/hello
quarkus.cxf.client.helloAllowAll.service-interface = io.quarkiverse.cxf.it.security.policy.HelloService
quarkus.cxf.client.helloAllowAll.trust-store = client-truststore.pkcs12
quarkus.cxf.client.helloAllowAll.trust-store-password = secret
quarkus.cxf.client.helloAllowAll.hostname-verifier = AllowAllHostnameVerifier
----

then an equivalent configuration for Quarkus CXF 3.16.0+ is

.application.properties
[source,properties]
----
# An equivalent configuration for Quarkus CXF 3.16.0+
quarkus.tls.helloAllowAll.trust-store.p12.path = client-truststore.pkcs12
quarkus.tls.helloAllowAll.trust-store.p12.password = secret
quarkus.tls.helloAllowAll.hostname-verification-algorithm = NONE
quarkus.cxf.client.helloAllowAll.client-endpoint-url = https://localhost:8444/services/hello
quarkus.cxf.client.helloAllowAll.service-interface = io.quarkiverse.cxf.it.security.policy.HelloService
quarkus.cxf.client.helloAllowAll.tls-configuration-name = helloAllowAll
----


=== https://github.com/quarkiverse/quarkus-cxf/issues/1447[#1447] Support asynchronous mode with `VertxHttpClientHTTPConduit`

Before {quarkus-cxf-project-name} 3.17.0, CXF clients based on `VertxHttpClientHTTPConduit` could only be called synchronously:

[source,java]
----
@CXFClient("hello")
HelloService hello;

String callHello() {
    // Synchronous CXF client call
    hello.hello("Joe");
}
----

{quarkus-cxf-project-name} 3.17.0 introduces the asynchronous mode for `VertxHttpClientHTTPConduit`-based clients:

[source,java]
----
import io.smallrye.mutiny.Uni;

@CXFClient("hello")
HelloService hello;

Uni<String> callHelloAsync() {
    return Uni.createFrom()
            // Asynchronous CXF client call returning java.util.concurrent.Future
            .future(hello.helloAsync("Joe"))
            .map(HelloResponse::getReturn);
}
----

This works much like with the existing Apache HttpClient 5 Async HTTP Transport.
The main difference is that you do not need to add (now deprecated) `io.quarkiverse.cxf:quarkus-cxf-rt-transports-http-hc5` dependency to your application anymore.

You still need to
xref:user-guide/advanced-client-topics/asynchronous-client.adoc#asynchronous-client-generate-async-methods[generate the async methods]
using the embedded `wsdl2java` tool.

Check the xref:user-guide/advanced-client-topics/asynchronous-client.adoc[Asynchronous client] page for more information.

=== https://github.com/quarkiverse/quarkus-cxf/issues/1609[#1609] Support HTTP redirects with `VertxHttpClientHTTPConduit`

Before {quarkus-cxf-project-name} 3.17.0, the `VertxHttpClientHTTPConduit`-based CXF clients were not following HTTP redirects
(HTTP status codes 301, 302, 303 and 307 with `Location` response header) even if
`xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-auto-redirect[quarkus.cxf.client."client-name".auto-redirect]`
was enabled for the given client.

{quarkus-cxf-project-name} 3.17.0 adds this functionality along with the proper support for
`xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-max-retransmits[quarkus.cxf.client."client-name".max-retransmits]`.

A new configuration property
`xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-redirect-relative-uri[quarkus.cxf.client."client-name".redirect-relative-uri]`
was introduced.
It is equivalent to setting `http.redirect.relative.uri` property on the CXF client request context as already supported by CXF.

=== https://github.com/quarkiverse/quarkus-cxf/issues/1639[#1639] Add `quarkus.cxf.client."client-name".max-same-uri` configuration option

Check
``xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-max-same-uri[quarkus.cxf.client."client-name".max-same-uri]``'s documentation for more information.
ifeval::[{doc-show-advanced-features} == true]

Special thanks to https://github.com/dcheng1248[@dcheng1248] for the https://github.com/quarkiverse/quarkus-cxf/pull/1669[contribution].
endif::[]

=== https://github.com/quarkiverse/quarkus-cxf/issues/1628[#1628] Support offloading the request data to disk with `VertxHttpClientHTTPConduit`

{quarkus-cxf-project-name} 3.17.0, added
xref:release-notes/3.17.0.adoc#_1609_support_http_redirects_with_vertxhttpclienthttpconduit[support for redirects] with `VertxHttpClientHTTPConduit`.
It included some basic in-memory caching of the request body for the sake of retransmission.
Since {quarkus-cxf-project-name} 3.18.0, the `VertxHttpClientHTTPConduit` is able
to offload the data to disk in case the size of the body surpasses some configurable threshold.
Check the documentation of the following new configuration options to learn how the new feature works:

* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-auto-redirect[quarkus.cxf.client."client-name".auto-redirect]`
* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-retransmit-cache-threshold[quarkus.cxf.retransmit-cache.threshold]`
* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-retransmit-cache-max-size[quarkus.cxf.retransmit-cache.max-size]`
* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-retransmit-cache-directory[quarkus.cxf.retransmit-cache.directory]`
* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-retransmit-cache-gc-delay[quarkus.cxf.retransmit-cache.gc-delay]`
* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-retransmit-cache-gc-on-shut-down[quarkus.cxf.retransmit-cache.gc-on-shut-down]`

[TIP]
====
The above configuration options also works for `URLConnectionHTTPConduit`.
====

=== https://github.com/quarkiverse/quarkus-cxf/issues/1616[#1616] Support authorization retransmits in `VertxHttpClientHTTPConduit`

Before {quarkus-cxf-project-name} 3.20.0, when a remote service responded with `401 Unauthorized` or `407 Proxy Authentication Required`,
 clients backed by `VertxHttpClientHTTPConduit` would simply fail
and the only possible workaround was to use some other HTTP conduit, such as `URLConnectionHTTPConduit`.

Since {quarkus-cxf-project-name} 3.20.0, `VertxHttpClientHTTPConduit` handles `401` and `407` status codes properly
by sending a new request with an `Authorization` header value derived from one or more of following options:

* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-auth-scheme[quarkus.cxf.client."client-name".auth.scheme]`
* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-auth-username[quarkus.cxf.client."client-name".auth.username]`
* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-auth-password[quarkus.cxf.client."client-name".auth.password]`
* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-auth-token[quarkus.cxf.client."client-name".auth.token]`
* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-proxy-username[quarkus.cxf.client."client-name".proxy-username]`
* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-proxy-password[quarkus.cxf.client."client-name".proxy-password]`

=== https://github.com/quarkiverse/quarkus-cxf/issues/1680[#1680] Introduce `quarkus.cxf.client.tls-configuration-name` to set TLS options for all CXF clients

Before {quarkus-cxf-project-name} 3.19.0, it was only possible to configure trust stores and key stores per CXF client via
`xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-tls-configuration-name[quarkus.cxf.client."client-name".tls-configuration-name]`
or (now deprecated)
`xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-key-store[quarkus.cxf.client."client-name".key-store*]`
and
`xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-trust-store[quarkus.cxf.client."client-name".trust-store*]` options.

In cases with multiple clients, this configuration could get verbose.

Since {quarkus-cxf-project-name} 3.19.0, it is possible to set the trust stores and key stores for all clients using the
`xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-tls-configuration-name[quarkus.cxf.client.tls-configuration-name]` option.


== Bugfixes
ifeval::[{doc-show-advanced-features} == true]

=== https://github.com/quarkiverse/quarkus-cxf/issues/1697[#1697] Native build fails when using `quarkus-cxf-integration-tracing-opentelemetry` and `quarkus-jdbc-oracle`

Before {quarkus-cxf-project-name} 3.19.0, combining `quarkus-jdbc-oracle` with `quarkus-cxf-integration-tracing-opentelemetry`
or `quarkus-cxf-rt-ws-rm` in a single application resulted in an error during the build of native image as follows:

[source]
----
org.graalvm.compiler.debug.GraalError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException:
Detected a MBean server in the image heap. This is currently not supported, but could be changed in the future.
Management beans are registered in many global caches that would need to be cleared and properly re-built at image build time.
Class of disallowed object: com.sun.jmx.mbeanserver.JmxMBeanServer
----

We have fixed this in {quarkus-cxf-project-name} 3.19.0.

NOTE: JMX features are still not supported in native mode.
endif::[]

=== https://github.com/quarkiverse/quarkus-cxf/issues/1326[#1326] https://issues.apache.org/jira/browse/CXF-9003[CXF-9003] Name clash between Service methods with the same name in one Java package

For each service method, several ancillary classes are generated at build time.
These may represent a request or a response of an operation.
So, for `com.acme.HelloService.hello()` method at least two classes `com.acme.jaxws_asm.Hello` and `com.acme.jaxws_asm.HelloResponse` would be generated.
Before {quarkus-cxf-project-name} 3.20.0 and CXF 4.1.1, the name of the service class was not taken into account.
Therefore, when there were multiple service interfaces containing methods with the same name in a single Java package,
then the names for their ancillary classes would clash.
This would mean that only one set of those classes, suiting only one of those services was stored in the application.
At runtime, the following error message may appear in the application log:

[source]
----
java.lang.IllegalArgumentException: argument type mismatch
     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
     at org.apache.cxf.databinding.AbstractWrapperHelper.createWrapperObject(AbstractWrapperHelper.java:114)
     at org.apache.cxf.jaxws.interceptors.WrapperClassOutInterceptor.handleMessage(WrapperClassOutInterceptor.java:91)
     at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
     at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:530)
     at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:441)
     at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:356)
     at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:314)
     at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
     at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:140)
     at jdk.proxy6/jdk.proxy6.$Proxy132.hello(Unknown Source)
----

The problem was fixed in CXF 4.1.1 and {quarkus-cxf-project-name} 3.20.0.
Now, the name of the service class is taken into account.
So for the above example, the names of the generated classes would be
`com.acme.jaxws_asm.helloservice.Hello` and `com.acme.jaxws_asm.helloservice.HelloResponse` respectively.

== Deprecations

=== https://github.com/quarkiverse/quarkus-cxf/issues/1633[#1633] `HttpClientHTTPConduitFactory` value of `*.http-conduit-factory` deprecated

The `HttpClientHTTPConduitFactory` value of
`xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-http-conduit-factory[quarkus.cxf.http-conduit-factory]`
and `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-http-conduit-factory[quarkus.cxf.client."client-name".http-conduit-factory]`
existed since their inception in {quarkus-cxf-project-name} 2.3.0.

`HttpClientHTTPConduit` never gained any real traction within {quarkus-cxf-project-name}.
When CXF started using it as a default, we were forced to introduce our own default (`URLConnectionHTTPConduitFactory`)
to avoid bugs like https://github.com/quarkiverse/quarkus-cxf/issues/992[#992],
https://issues.apache.org/jira/browse/CXF-8885[CXF-8885],
https://issues.apache.org/jira/browse/CXF-8951[CXF-8951],
https://issues.apache.org/jira/browse/CXF-8946[CXF-8946],
https://issues.apache.org/jira/browse/CXF-8903[CXF-8903] and possibly others.
Now that we have `VertxHttpClientHTTPConduit`,
which we can support very well on Quarkus,
there are no more reasons for us to spend our resources on `HttpClientHTTPConduit`.

`HttpClientHTTPConduitFactory` was marked as deprecated in our documentation and we added some warnings on application startup for folks still using it.

=== https://github.com/quarkiverse/quarkus-cxf/issues/1632[#1632] `io.quarkiverse.cxf:quarkus-cxf-rt-transports-http-hc5` deprecated

The `io.quarkiverse.cxf:quarkus-cxf-rt-transports-http-hc5` extension is deprecated since {quarkus-cxf-project-name} 3.19.0
and it is scheduled for removal in 3.21.0.
Use the xref:user-guide/advanced-client-topics/asynchronous-client.adoc[asynchronous mode of `VertxHttpClientHTTPConduit`] instead.

This is a part of our efforts to support only a single HTTP Conduit based on Vert.x HttpClient in the future.

=== Deprecated configuration properties

* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-username[quarkus.cxf.client."client-name".username]` - use
  `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-auth-username[quarkus.cxf.client."client-name".auth.username]` instead
* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-password[quarkus.cxf.client."client-name".password]` - use
  `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-auth-password[quarkus.cxf.client."client-name".auth.password]` instead
* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-key-store[quarkus.cxf.client."client-name".key-store]` - use
  `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-tls-configuration-name[quarkus.cxf.client."client-name".auth.tls-configuration-name]` instead
* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-key-store-password[quarkus.cxf.client."client-name".key-store-password]` - use
  `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-tls-configuration-name[quarkus.cxf.client."client-name".auth.tls-configuration-name]` instead
* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-key-store-type[quarkus.cxf.client."client-name".key-store-type]` - use
  `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-tls-configuration-name[quarkus.cxf.client."client-name".auth.tls-configuration-name]` instead
* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-key-password[quarkus.cxf.client."client-name".key-password]` - use
  `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-tls-configuration-name[quarkus.cxf.client."client-name".auth.tls-configuration-name]` instead
* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-trust-store[quarkus.cxf.client."client-name".trust-store]` - use
  `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-tls-configuration-name[quarkus.cxf.client."client-name".auth.tls-configuration-name]` instead
* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-trust-store-password[quarkus.cxf.client."client-name".trust-store-password]` - use
  `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-tls-configuration-name[quarkus.cxf.client."client-name".auth.tls-configuration-name]` instead
* `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-trust-store-type[quarkus.cxf.client."client-name".trust-store-type]` - use
  `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-tls-configuration-name[quarkus.cxf.client."client-name".auth.tls-configuration-name]` instead


== Full changelog

https://github.com/quarkiverse/quarkus-cxf/compare/3.15.3+++...+++3.20.2
