= {quarkus-cxf-project-name} 3.27.2 LTS release notes

== Important dependency upgrades

* Quarkus 3.27.0 -> 3.27.3.1
** https://quarkus.io/blog/quarkus-3-27-3-released/[Release notes 3.27.3]
*** Fixes https://nvd.nist.gov/vuln/detail/CVE-2026-1002[CVE-2026-1002] and https://nvd.nist.gov/vuln/detail/CVE-2025-33042[CVE-2025-33042]
** https://quarkus.io/blog/CVE-2026-39852/[Release notes 3.27.3.1]
*** Fixes https://github.com/quarkusio/quarkus/security/advisories/GHSA-rc95-pcm8-65v9[CVE-2026-39852]
* Apache CXF 4.1.3 -> 4.1.4 - link:https://github.com/apache/cxf/compare/cxf-4.1.3+++...+++cxf-4.1.4[changelog]
* Apache Neethi 3.2.1 -> 3.2.2 - https://www.cve.org/CVERecord?id=CVE-2026-42404[CVE-2026-42404],
  https://www.cve.org/CVERecord?id=CVE-2026-42403[CVE-2026-42403] and https://www.cve.org/CVERecord?id=CVE-2026-42402[CVE-2026-42402] fixed.

== Bugfixes

=== https://github.com/quarkiverse/quarkus-cxf/issues/2060[#2060] Avoid using `HttpClientHTTPConduit` even for clients created via `jakarta.xml.ws.Service.create(URL, QName).getPort(MyService.class)`

`HttpClientHTTPConduit` provided by CXF has had known issues, so we deprecated the `HttpClientHTTPConduitFactory` value of
`xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-http-conduit-factory[quarkus.cxf.http-conduit-factory]`
and `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-client-client-name-http-conduit-factory[quarkus.cxf.client."client-name".http-conduit-factory]`
options in xref:release-notes/3.18.0.adoc#issue_1633_httpclienthttpconduitfactory_value_deprecated[3.18.0 release].
We removed the `HttpClientHTTPConduitFactory` value in
xref:release-notes/3.22.0.adoc#_remove_httpclienthttpconduitfactory_value_of_http_conduit_factory[{quarkus-cxf-project-name} 3.22.0].
So after 3.22.0 it was not possible to xref:user-guide/first-soap-client.adoc[create an injected SOAP client]
via {quarkus-cxf-project-name} `application.properties` configuration that would use `HttpClientHTTPConduit` and JDK HTTP Client under the hood.

However, even after {quarkus-cxf-project-name} 3.22.0 it was still possible to programmatically create SOAP clients using `HttpClientHTTPConduit` as follows:

[source,java]
----
URL serviceUrl = ...;
QName qName = ...
Service service = Service.create(serviceUrl, qName);
MyService myClient = service.getPort(MyService.class);
----

The issue https://github.com/quarkiverse/quarkus-cxf/issues/2060[#2060] popped up in our MTOM integration test,
which spawns many SOAP clients to perform some soak testing.
When the number of clients went over certain threshold, the clients started failing due to underlying HTTP connections being closed.
This is another known issue of JDK HTTP client: no external control over its internal connection pool is possible.
Connections may get closed while SOAP clients still use them, possibly running in parallel threads.

Since {quarkus-cxf-project-name} 3.35.0, 3.33.2 and 3.27.2, even clients created programmatically via
`jakarta.xml.ws.Service.create(URL, QName).getPort(MyService.class)` are using `URLConnectionHTTPConduit` instead of `HttpClientHTTPConduit`.
As a consequence of that, no issues with connection pooling should occur.

== Full changelog

https://github.com/quarkiverse/quarkus-cxf/compare/3.27.1+++...+++3.27.2
