= {quarkus-cxf-project-name} 3.40.0 LTS release notes

// AI-generated by Codex on behalf of Peter Palaga.

3.40.0 is the first release in the 3.40 long term support (LTS) stream.

== Important dependency upgrades

* Quarkus 3.39.0 -> 3.40.0 - https://quarkus.io/blog/quarkus-3-40-released/[release notes], link:https://github.com/quarkusio/quarkus/compare/3.39.0+++...+++3.40.0[changelog]

The Quarkus upgrade includes the following security fixes in Quarkus and its managed dependencies.
These apply to applications using the affected components.
See also the https://quarkus.io/blog/quarkus-3-39-2-released/[Quarkus 3.39.2]
and https://quarkus.io/blog/quarkus-3-39-5-released/[Quarkus 3.39.5] announcements for details:

* Quarkus Qute: https://www.cve.org/CVERecord?id=CVE-2026-12894[CVE-2026-12894],
  https://www.cve.org/CVERecord?id=CVE-2026-93432[CVE-2026-93432]
* Quarkus OIDC: https://www.cve.org/CVERecord?id=CVE-2026-19625[CVE-2026-19625]
* Quarkus Spring Web: https://www.cve.org/CVERecord?id=CVE-2026-19651[CVE-2026-19651]
* Quarkus WebSockets Next: https://www.cve.org/CVERecord?id=CVE-2026-87742[CVE-2026-87742]
* Quarkus Vert.x HTTP: https://www.cve.org/CVERecord?id=CVE-2026-87743[CVE-2026-87743]
* RESTEasy: https://www.cve.org/CVERecord?id=CVE-2026-17615[CVE-2026-17615],
  https://www.cve.org/CVERecord?id=CVE-2026-89058[CVE-2026-89058],
  https://www.cve.org/CVERecord?id=CVE-2026-89059[CVE-2026-89059]
* SmallRye GraphQL: https://www.cve.org/CVERecord?id=CVE-2026-76763[CVE-2026-76763]
* SmallRye JWT: https://www.cve.org/CVERecord?id=CVE-2026-81829[CVE-2026-81829]
* SmallRye Fault Tolerance: https://www.cve.org/CVERecord?id=CVE-2026-94449[CVE-2026-94449]
* Hibernate ORM: https://www.cve.org/CVERecord?id=CVE-2026-77874[CVE-2026-77874]
* Apache FreeMarker: https://www.cve.org/CVERecord?id=CVE-2026-84939[CVE-2026-84939]
* zstd-jni: https://www.cve.org/CVERecord?id=CVE-2026-87825[CVE-2026-87825],
  https://www.cve.org/CVERecord?id=CVE-2026-87877[CVE-2026-87877],
  https://www.cve.org/CVERecord?id=CVE-2026-87795[CVE-2026-87795],
  https://www.cve.org/CVERecord?id=CVE-2026-87824[CVE-2026-87824],
  https://www.cve.org/CVERecord?id=CVE-2026-89046[CVE-2026-89046],
  https://www.cve.org/CVERecord?id=CVE-2026-87823[CVE-2026-87823],
  https://www.cve.org/CVERecord?id=CVE-2026-90560[CVE-2026-90560],
  https://www.cve.org/CVERecord?id=CVE-2026-90852[CVE-2026-90852],
  https://www.cve.org/CVERecord?id=CVE-2026-89045[CVE-2026-89045]
* Netty: https://www.cve.org/CVERecord?id=CVE-2026-93491[CVE-2026-93491],
  https://www.cve.org/CVERecord?id=CVE-2026-93558[CVE-2026-93558],
  https://www.cve.org/CVERecord?id=CVE-2026-93564[CVE-2026-93564],
  https://www.cve.org/CVERecord?id=CVE-2026-93565[CVE-2026-93565],
  https://www.cve.org/CVERecord?id=CVE-2026-93567[CVE-2026-93567],
  https://www.cve.org/CVERecord?id=CVE-2026-93568[CVE-2026-93568],
  https://www.cve.org/CVERecord?id=CVE-2026-93569[CVE-2026-93569],
  https://www.cve.org/CVERecord?id=CVE-2026-93492[CVE-2026-93492],
  https://www.cve.org/CVERecord?id=CVE-2026-93562[CVE-2026-93562],
  https://www.cve.org/CVERecord?id=CVE-2026-93566[CVE-2026-93566],
  https://www.cve.org/CVERecord?id=CVE-2026-93573[CVE-2026-93573],
  https://www.cve.org/CVERecord?id=CVE-2026-93574[CVE-2026-93574],
  https://www.cve.org/CVERecord?id=CVE-2026-93579[CVE-2026-93579]

== Bugfixes

=== https://github.com/quarkiverse/quarkus-cxf/issues/2283[#2283] `NullPointerException` during re-augmentation of a `mutable-jar` application

Before {quarkus-cxf-project-name} 3.40.0, applications using version 3.39.0 or 3.39.1,
packaged with `quarkus.package.jar.type=mutable-jar` and launched with `-Dquarkus.launch.rebuild=true`,
failed during re-augmentation with `NullPointerException: inStream parameter is null`.
The failure occurred while replacing the CXF WS-Addressing message resource bundle,
which was not available through the class loader used during re-augmentation.

Since {quarkus-cxf-project-name} 3.40.0, the WS-Addressing messages are overridden using bytecode transformation,
and re-augmentation succeeds.
The messages continue to refer to the configuration options
xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-endpoint-addressing-decoupled-enabled[quarkus.cxf.endpoint.addressing.decoupled.enabled]
and xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-endpoint-addressing-decoupled-allowed-schemes[quarkus.cxf.endpoint.addressing.decoupled.allowed-schemes].

Special thanks to https://github.com/narcismatei[@narcismatei] for reporting the issue.

== Documentation improvements

* The section landing pages now explain the tasks covered by each section and help readers find the relevant guides.
* The JAXB and Apache CXF XJC Plugins extension pages explain what XJC is and how the plugins extend code generation.
* The WS-Security configuration reference clarifies which options have not been tested with {quarkus-cxf-project-name}.
* The link to the xref:user-guide/advanced-client-topics/asynchronous-client.adoc#caller-threads-and-callback-threads[Caller threads and callback threads]
  section now works with customized documentation anchor settings.

Special thanks to https://github.com/rolfedh[@rolfedh] for the landing page and documentation link improvements.

== Full changelog

https://github.com/quarkiverse/quarkus-cxf/compare/3.39.1+++...+++3.40.0
