= {quarkus-cxf-project-name} 3.40.0 LTS release notes

3.40.0 is the first release in the 3.40 long term support (LTS) stream.

== Important dependency upgrades

* Quarkus 3.39.0 -> 3.40.0 - https://quarkus.io/blog/quarkus-3-40-released/[release notes], link:https://github.com/quarkusio/quarkus/compare/3.39.0+++...+++3.40.0[changelog]

== Bugfixes

=== https://github.com/quarkiverse/quarkus-cxf/issues/2283[#2283] `NullPointerException` during re-augmentation of a `mutable-jar` application

Before {quarkus-cxf-project-name} 3.40.0, applications using version 3.39.0 or 3.39.1,
packaged with `quarkus.package.jar.type=mutable-jar` and launched with `-Dquarkus.launch.rebuild=true`,
failed during re-augmentation with `NullPointerException: inStream parameter is null`.
The failure occurred while replacing the CXF WS-Addressing message resource bundle,
which was not available through the class loader used during re-augmentation.
We did this for the sake of user convenience: the log and error messages emitted by CXF mentioned CXF-specific
system properties that were not honored by Quarkus CXF.
So we replaced those by messages mentioning equivalent Quarkus CXF configutation options.

Since {quarkus-cxf-project-name} 3.40.0, the WS-Addressing messages are overridden using bytecode transformation,
and re-augmentation succeeds.
The messages continue to refer to the configuration options
xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-endpoint-addressing-decoupled-enabled[quarkus.cxf.endpoint.addressing.decoupled.enabled]
and xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-endpoint-addressing-decoupled-allowed-schemes[quarkus.cxf.endpoint.addressing.decoupled.allowed-schemes].

Special thanks to https://github.com/narcismatei[@narcismatei] for reporting the issue.

== Documentation improvements

* The section landing pages now explain the tasks covered by each section and help readers find the relevant guides.
* The JAXB and Apache CXF XJC Plugins extension pages explain what XJC is and how the plugins extend code generation.
* The WS-Security configuration reference clarifies which options have not been tested with {quarkus-cxf-project-name}.
* The link to the xref:user-guide/advanced-client-topics/asynchronous-client.adoc#caller-threads-and-callback-threads[Caller threads and callback threads]
  section now works with customized documentation anchor settings.

Special thanks to https://github.com/rolfedh[@rolfedh] for the landing page and documentation link improvements.

== Full changelog

https://github.com/quarkiverse/quarkus-cxf/compare/3.39.1+++...+++3.40.0
