[[rn-3-9-0]]
= {quarkus-cxf-project-name} 3.9.0 release notes

== Important dependency upgrades

* Quarkus 3.8.2 -> 3.9.0 - https://quarkus.io/blog/quarkus-3-9-1-released/[3.9 release notes]

== New and noteworthy in {quarkus-cxf-project-name}

=== Change in `org.graalvm.sdk:*` dependencies

{quarkus-cxf-project-name} extensions now depend on `org.graalvm.sdk:nativeimage` instead of `org.graalvm.sdk:graal-sdk`.
Using `org.graalvm.sdk:graal-sdk` was an oversight on our side.
`org.graalvm.sdk:nativeimage` is just enough for implementing the GraalVM substitutions we need.
If you rely on other transitive dependencies of `org.graalvm.sdk:graal-sdk`, such as `org.graalvm.sdk:polyglot` or `org.graalvm.sdk:collections`,
you will have to add them yourself.

=== Improved documentation

The following parts of the documentation were improved:

* We published a bunch of xref:release-notes/index.adoc#release-notes-index[release notes] for older {quarkus-cxf-project-name} versions 2.2.x through 2.7.x.
* Build time configuration options, such as `xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf_quarkus-cxf-codegen-wsdl2java-enabled[quarkus.cxf.codegen.wsdl2java.*]` were missing in on the `quarkus-cxf` reference page due to a bug in our tooling.
* We added xref:release-notes/index.adoc#version-table[Version table] to the release notes page.
  It shows which Quarkus CXF version is available in which Quarkus Platform version and which CXF version it depends on.

== Full changelog

https://github.com/quarkiverse/quarkus-cxf/compare/3.8.1+++...+++3.9.0
