[[rn-3-14-0]]
= {quarkus-cxf-project-name} 3.14.0 release notes

== Important dependency upgrades

* Quarkus 3.13.x -> 3.14.0 - https://quarkus.io/blog/quarkus-3-14-1-released/[release notes]

== New and noteworthy in {quarkus-cxf-project-name}

=== https://github.com/quarkiverse/quarkus-cxf/issues/1460[#1460] IllegalArgumentException: port p must be in range 0 <= p <= 65535 when using client-endpoint-url without explicit port

When using the xref:release-notes/rn-3-13-0.adoc#_vert_x_httpclient_based_http_conduit[new `VertxHttpClientHTTPConduitFactory`],
the handling of default ports for `http` and `https` client endpoint URLs was broken resulting in an `IllegalArgumentException`.
This was fixed in {quarkus-cxf-project-name} 3.14.0.

=== https://github.com/quarkiverse/quarkus-cxf/issues/1476[#1476] Missing dependency for OpenTelemetryCustomizer when OTEL is globally disabled

If OpenTelemetry was disabled via `quarkus.otel.enabled = false`,
then any Quarkus CXF application using `quarkus-cxf-integration-tracing-opentelemetry` would fail at application start
throwing an exception like the following:

----
Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
    [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.opentelemetry.api.OpenTelemetry and qualifiers [@Default]
    - injection target: io.quarkiverse.cxf.opentelemetry.OpenTelemetryCustomizer#openTelemetry
    - declared on CLASS bean [types=[io.quarkiverse.cxf.CxfClientProducer$ClientFactoryCustomizer, io.quarkiverse.cxf.transport.CxfHandler$EndpointFactoryCustomizer, java.lang.Object, io.quarkiverse.cxf.opentelemetry.OpenTelemetryCustomizer], qualifiers=[@Default, @Any], target=io.quarkiverse.cxf.opentelemetry.OpenTelemetryCustomizer]
----

Since version 3.14.0, the `quarkus-cxf-integration-tracing-opentelemetry` extension checks the value of `quarkus.otel.enabled` at build time
and if the value is `false`, it disables OpenTelemetry for CXF too.

=== Documentation improvements

Some substantial refactoring took place in the way how we generate the documentation for the
xref:reference/extensions/quarkus-cxf.adoc#quarkus-cxf-configuration[configuration]
xref:reference/extensions/quarkus-cxf-rt-ws-security.adoc#quarkus-cxf-rt-ws-security-configuration[options].
Although there are not many https://github.com/quarkiverse/quarkus-cxf/commit/b8913f7fcc58ced6cec9b7c1dc505cfcdd9088f4[observable changes],
please do not hesitate to https://github.com/quarkiverse/quarkus-cxf/issues/new[file an issue] if you spot some irregularity.

== Full changelog

https://github.com/quarkiverse/quarkus-cxf/compare/3.13.1+++...+++3.14.0
