[[rn-3-8-6]]
= {quarkus-cxf-project-name} 3.8.6 (LTS) release notes

== Important dependency upgrades:

* Quarkus 3.8.5 -> 3.8.6 - https://quarkus.io/blog/quarkus-3-8-6-released/[release notes]
* CXF 4.0.4 -> 4.0.5 - https://cxf.apache.org/download.html[release notes], link:https://github.com/apache/cxf/compare/cxf-4.0.4+++...+++cxf-4.0.5[changelog]

== New and noteworthy in {quarkus-cxf-project-name}

=== https://github.com/quarkiverse/quarkus-cxf/issues/1416[#1416] passing multiple namespace mappings via `quarkus.cxf.codegen.wsdl2java.package-names`

Before {quarkus-cxf-project-name} 3.13.0 and 3.8.6, the values specified in
`xref:reference/extensions/quarkus-cxf.adoc[quarkus.cxf.codegen.wsdl2java.package-names]`
were wrongly passed as a single comma-separated value of the `-p` option,
leading to `BadUsageException: -p has invalid character!`.

Since {quarkus-cxf-project-name} 3.13.0 and 3.8.6, if `quarkus.cxf.codegen.wsdl2java.package-names` specifies multiple mappings, such as

.application.properties
[source,properties]
----
quarkus.cxf.codegen.wsdl2java.package-names =
  http://www.example.org/add=io.quarkiverse.cxf.wsdl2java.it.add,
  http://www.example.org/multiply=io.quarkiverse.cxf.wsdl2java.it.multiply
----

then they are properly passed to `wsdl2java` as multiple `-p` options:

.application.properties
[source,console]
----
wsdl2java \
  -p http://www.example.org/add=io.quarkiverse.cxf.wsdl2java.it.add \
  -p http://www.example.org/multiply=io.quarkiverse.cxf.wsdl2java.it.multiply \
  ...
----

== Full changelog

https://github.com/quarkiverse/quarkus-cxf/compare/3.8.5+++...+++3.8.6
