[[rn-3-8-0]]
= {quarkus-cxf-project-name} 3.8.0 (LTS) release notes

== Changes in Quarkus

* See https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.8[Quarkus 3.8 migration guide].

== New and noteworthy in {quarkus-cxf-project-name}

=== Keeping `major.minor` version in sync with Quarkus

The most significant change in this release is the increment of major version of {quarkus-cxf-project-name} from 2 to 3
so that our `major.minor` matches the `major.minor` version of Quarkus.

We did this mostly for practical reasons, so that it is easier for everybody to understand which version of {quarkus-cxf-project-name}
is compatible with which version of Quarkus.

=== Logging extension removed from the documentation and {link-quarkus-code-generator}

`io.quarkiverse.cxf:quarkus-cxf-rt-features-logging` is deprecated since {quarkus-cxf-project-name} 2.7.0,
when all its functionality including configuration properties moved to `io.quarkiverse.cxf:quarkus-cxf`.
In 3.8.0, we stopped mentioning it in the documentation and we removed it from {link-quarkus-code-generator}.
To keep backwards compatibility, a dummy `io.quarkiverse.cxf:quarkus-cxf-rt-features-logging` artifact still exists
doing nothing else, but outputting a warning.
You should remove the extension from your projects.

=== Santuario XMLSec extension moved to {quarkus-cxf-project-name}

Santuario XMLSec extension was originally hosted under a https://github.com/quarkiverse/quarkus-xmlsec[separate project]
and published as `io.quarkiverse.xmlsec:quarkus-xmlsec`.
As {quarkus-cxf-project-name} is the primary user of it, we decided to move it here to simplify the maintenance.
The new Maven coordinates starting with {quarkus-cxf-project-name} 3.8.0 are `io.quarkiverse.cxf:quarkus-cxf-santuario-xmlsec`.

=== Improved documentation

The following parts of the documentation were improved:

* The Reference page now contains xref:reference/index.adoc#supported-cxf-annotations[List of supported CXF annotations].
* xref:reference/extensions/quarkus-cxf-rt-ws-security.adoc#quarkus-cxf-rt-ws-security[WS-Security extension page]
** New example using xref:reference/index.adoc#extensions-quarkus-cxf-rt-ws-security-usage-ws-security-via-ws-securitypolicy[WS-SecurityPolicy]
** New configuration options for xref:reference/extensions/quarkus-cxf-rt-ws-security.adoc#quarkus-cxf_quarkus-cxf-client-client-name-security-sts-client[STSClient]
* xref:reference/extensions/quarkus-cxf-services-sts.adoc#quarkus-cxf-services-sts[Security Token Service (STS) extension page] with a more detailed example

== Full changelog

https://github.com/quarkiverse/quarkus-cxf/compare/2.7.1+++...+++3.8.0
