name: rebase-integration-branch

on:
  workflow_dispatch:
  schedule:
    # Run every day at 2AM
    - cron:  '0 2 * * *'

env:
  LANG: en_US.UTF-8
  JAVA_VERSION: 17

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write
  issues: write

jobs:
  rebase-integration-branch:
    if: github.repository == 'quarkiverse/quarkus-cxf'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dependency-short-name: 'quarkus'
            dependency-stream: 'main'
            dependency-branch: 'main'
            issue-id: 1287
            base-branch: 'main'
            dependency-git-repo-url: https://github.com/quarkusio/quarkus.git
          - dependency-short-name: 'cxf'
            dependency-stream: 'main'
            dependency-branch: 'main'
            issue-id: 1767
            base-branch: 'main'
            dependency-git-repo-url: https://github.com/apache/cxf.git

    steps:

    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}

    - name: rebase-dependency-main-branch
      uses: ./.github/actions/rebase-dependency-main-branch
      id: rebase-dependency-main-branch
      with:
        dependency-git-repo-url: ${{ matrix.dependency-git-repo-url }}
        dependency-short-name: ${{ matrix.dependency-short-name }}
        dependency-stream: ${{ matrix.dependency-stream }}
        dependency-branch: ${{ matrix.dependency-branch }}
        issue-id: ${{ matrix.issue-id }}
        token: "${{ secrets.GITHUB_TOKEN }}"

    - name: Show steps.rebase-dependency-main-branch.outputs.exit-status
      shell: bash
      run: |
        echo "steps.rebuild-dependency.outputs.exit-status: ${{ steps.rebase-dependency-main-branch.outputs.exit-status }}"

    - name: build-and-run-jvm-tests
      uses: ./.github/actions/build-and-run-jvm-tests
      with:
        run-native-tests: 'true'

    - name: git push origin ${{ matrix.dependency-short-name }}-${{ matrix.dependency-stream }} -f
      shell: bash
      run: |
        lastCommitMessage="$(git log -1 --pretty=%B)"
        echo "Comparing last commit message '$lastCommitMessage' with '${{ steps.rebase-dependency-main-branch.outputs.upgrade-message }}'"
        if [[ "$lastCommitMessage" == "${{ steps.rebase-dependency-main-branch.outputs.upgrade-message }}" ]]; then
          echo "Removing last commit '$lastCommitMessage'"
          git reset --hard HEAD~1
        else
          echo "Not removing the last commit because its message is not '${{ steps.rebase-dependency-main-branch.outputs.upgrade-message }}' but '$lastCommitMessage'"
        fi
        git push origin ${{ matrix.dependency-short-name }}-${{ matrix.dependency-stream }} -f

    - name: Reopen issue https://github.com/${{ github.repository }}/issues/${{ matrix.issue-id }}
      if: ${{ steps.rebase-dependency-main-branch.outputs.exit-status == 'success' && failure() }}
      shell: bash
      run: |
        oldState=$(gh issue view ${{ matrix.issue-id }} --json state -q .state -R ${{ github.repository }})
        echo "oldState = $oldState"
        msg="❌ Build with ${{ matrix.dependency-short-name }} ${{ steps.rebase-dependency-main-branch.outputs.dependency-commit }} failed in ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        if [[ "$oldState" == "OPEN" ]] ; then
          gh issue comment \
            --repo ${{ github.repository }} \
            --body "$msg" \
            ${{ matrix.issue-id }}
        else
          gh issue reopen \
            --repo ${{ github.repository }} \
            --comment "$msg" \
            ${{ matrix.issue-id }}
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Close issue https://github.com/${{ github.repository }}/issues/${{ matrix.issue-id }}
      if: ${{ success() }}
      shell: bash
      run: |
        oldState=$(gh issue view ${{ matrix.issue-id }} --json state -q .state -R ${{ github.repository }})
        echo "oldState = $oldState"
        msg="✅ Build with ${{ matrix.dependency-short-name }} ${{ steps.rebase-dependency-main-branch.outputs.dependency-commit }} succeeded in ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        if [[ "$oldState" != "CLOSED" ]] ; then
          gh issue close \
            --repo ${{ github.repository }} \
            --comment "$msg" \
            ${{ matrix.issue-id }}
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

