name: Quarkiverse Prepare Release

on:
  pull_request:
    types: [ closed ]
    paths:
      - '.github/project.yml'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare-release:
    name: Prepare Release
    if: ${{ github.event.pull_request.merged == true}}
    uses: quarkiverse/.github/.github/workflows/prepare-release.yml@main
    secrets: inherit
    with:
      java_version: 17

  edit-release-notes:
    name: Edit Release Notes
    needs: prepare-release
    runs-on: ubuntu-latest
    steps:
      - name: Change release notes
        run: gh release edit ${RELEASE_VERSION} -n "https://docs.quarkiverse.io/quarkus-cxf/dev/release-notes/${RELEASE_VERSION}.html"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ needs.prepare-release.outputs.release-version }}
